import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguageCode = 'en'; // Default to English

  String get currentLanguageCode => _currentLanguageCode;

  // Language configurations
  final Map<String, Map<String, String>> _languages = {
    'en': {'name': 'English', 'native': 'English'},
    'fr': {'name': 'Français', 'native': 'French'},
    'hi': {'name': 'हिंदी', 'native': 'Hindi'},
    'es': {'name': 'Español', 'native': 'Spanish'},
    'ta': {'name': 'தமிழ்', 'native': 'Tamil'},
    'ms': {'name': 'Bahasa Melayu', 'native': 'Malay'},
    'bn': {'name': 'বাংলা', 'native': 'Bangla'},
    'uz': {'name': 'O\'zbek', 'native': 'Uzbek'},
    'ru': {'name': 'Русский', 'native': 'Russian'},
  };

  Map<String, Map<String, String>> get languages => _languages;

  String get currentLanguageName => _languages[_currentLanguageCode]?['name'] ?? 'English';

  // Load saved language preference
  Future<void> loadLanguagePreference() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLanguage = prefs.getString('app_language');
      if (savedLanguage != null && _languages.containsKey(savedLanguage)) {
        _currentLanguageCode = savedLanguage;
        notifyListeners();
      }
    } catch (e) {
      debugPrint('Error loading language preference: $e');
    }
  }

  // Change language and persist
  Future<void> changeLanguage(String languageCode) async {
    if (_languages.containsKey(languageCode)) {
      _currentLanguageCode = languageCode;

      // Save to SharedPreferences
      try {
        final prefs = await SharedPreferences.getInstance();
        await prefs.setString('app_language', languageCode);
      } catch (e) {
        debugPrint('Error saving language preference: $e');
      }

      notifyListeners();
    }
  }

  // Get translation for a key
  String translate(String key) {
    return _translations[_currentLanguageCode]?[key] ??
           _translations['en']?[key] ??
           key;
  }

  // Short form for translation
  String t(String key) => translate(key);

  // Translations map
  final Map<String, Map<String, String>> _translations = {
    'en': {
      // Common
      'app_name': 'MaxBillUp',
      'welcome': 'Welcome',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'update': 'Update',
      'search': 'Search',
      'settings': 'Settings',
      'logout': 'Logout',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'done': 'Done',
      'loading': 'Loading...',
      'coming_soon': 'Coming soon',
      'used': 'Used',
      'error': 'Error',
      'success': 'Success',

      // Navigation
      'home': 'Home',
      'sales': 'Sales',
      'stocks': 'Stocks',
      'reports': 'Reports',
      'menu': 'Menu',

      // Sales
      'new_sale': 'New Sale',
      'sale_all': 'Sale All',
      'quick_sale': 'Quick Sale',
      'saved_orders': 'Saved Orders',
      'save_order': 'Save Order',
      'complete_payment': 'Complete Payment',
      'add_to_cart': 'Add to Cart',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'payment_mode': 'Payment Mode',
      'cash': 'Cash',
      'online': 'Online',
      'credit': 'Credit',
      'split_payment': 'Split Payment',

      // Bill
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'tax': 'Tax',
      'total': 'Total',
      'grand_total': 'Grand Total',
      'amount_received': 'Amount Received',
      'change': 'Change',
      'customer': 'Customer',
      'add_customer': 'Add Customer',

      // Products/Stocks
      'products': 'Products',
      'category': 'Category',
      'addproduct': 'Add Product',
      'price': 'Price',
      'cost_price': 'Cost Price',
      'mrp': 'MRP',
      'quantity': 'Quantity',
      'barcode': 'Barcode',
      'stock': 'Stock',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'low_stock': 'Low Stock',

      // Tax
      'tax_settings': 'Tax Settings',
      'add_tax': 'Add Tax',
      'tax_name': 'Tax Name',
      'tax_percentage': 'Tax %',
      'price_includes_tax': 'Price includes Tax',
      'price_without_tax': 'Price is without Tax',
      'zero_rated_tax': 'Zero Rated Tax',
      'exempt_tax': 'Exempt Tax',

      // Settings
      'profile': 'Profile',
      'business_details': 'Business Details',
      'business_name': 'Business Name',
      'business_phone': 'Business Phone',
      'business_location': 'Business Location',
      'business_email': 'Business Email',
      'gstin': 'GSTIN',
      'choose_language': 'Choose Language',
      'theme': 'Theme',
      'printer_setup': 'Printer Setup',
      'receipt_customization': 'Receipt Customization',
      'feature_settings': 'Feature Settings',
      'help': 'Help',
      'about': 'About',

      // Reports
      'daily_report': 'Daily Report',
      'monthly_report': 'Monthly Report',
      'sales_report': 'Sales Report',
      'stock_report': 'Stock Report',
      'tax_report': 'Tax Report',
      'profit_loss': 'Profit & Loss',

      // Messages
      'product_added': 'Product added successfully',
      'product_updated': 'Product updated successfully',
      'product_deleted': 'Product deleted successfully',
      'sale_completed': 'Sale completed successfully',
      'payment_successful': 'Payment successful',
      'payment_failed': 'Payment failed',
      'no_items_in_cart': 'No items in cart',
      'invalid_input': 'Invalid input',
      'required_field': 'This field is required',
      'confirm_delete': 'Are you sure you want to delete?',
      'saved_offline': 'Saved offline. Will sync when online.',
      'sync_completed': 'Sync completed',

      // Additional Pages
      'quotations': 'Quotations',
      'create_quotation': 'Create Quotation',
      'quotation_list': 'Quotation List',
      'convert_to_sale': 'Convert to Sale',
      'expenses': 'Expenses',
      'other_expenses': 'Other Expenses',
      'add_expense': 'Add Expense',
      'expense_category': 'Expense Category',
      'categories': 'Categories',
      'add_category': 'Add Category',
      'staff_management': 'Staff Management',
      'add_staff': 'Add Staff',
      'customer_management': 'Customer Management',
      'customers': 'Customers',
      'supplier': 'Supplier',
      'purchase': 'Purchase',
      'stock_purchase': 'Stock Purchase',
      'view': 'View',
      'print': 'Print',
      'share': 'Share',
      'invoice': 'Invoice',
      'receipt': 'Receipt',
      'date': 'Date',
      'time': 'Time',
      'from': 'From',
      'to': 'To',
      'all': 'All',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'custom': 'Custom',
      'apply': 'Apply',
      'reset': 'Reset',
      'export': 'Export',
      'download': 'Download',
      'upload': 'Upload',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'finish': 'Finish',
      'skip': 'Skip',
      'continue': 'Continue',
      'close': 'Close',
      'open': 'Open',
      'refresh': 'Refresh',
      'sync': 'Sync',
      'online_mode': 'Online Mode',
      'offline_mode': 'Offline Mode',
      'select': 'Select',
      'select_all': 'Select All',
      'deselect_all': 'Deselect All',
      'filter': 'Filter',
      'sort': 'Sort',
      'ascending': 'Ascending',
      'descending': 'Descending',
      'name': 'Name',
      'description': 'Description',
      'amount': 'Amount',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'pending': 'Pending',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'active': 'Active',
      'inactive': 'Inactive',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'phone': 'Phone',
      'email': 'Email',
      'address': 'Address',
      'city': 'City',
      'state': 'State',
      'country': 'Country',
      'pincode': 'Pincode',
      'notes': 'Notes',
      'remarks': 'Remarks',
      'status': 'Status',
      'action': 'Action',
      'actions': 'Actions',
      'details': 'Details',
      'summary': 'Summary',
      'billing': 'Billing',
      'shipping': 'Shipping',
      'payment': 'Payment',
      'order': 'Order',
      'orders': 'Orders',
      'item': 'Item',
      'items': 'Items',
      'unit': 'Unit',
      'rate': 'Rate',
      'gst': 'GST',
      'vat': 'VAT',
      'cgst': 'CGST',
      'sgst': 'SGST',
      'igst': 'IGST',
      'total_items': 'Total Items',
      'total_amount': 'Total Amount',
      'due_amount': 'Due Amount',
      'balance': 'Balance',
      'credit_limit': 'Credit Limit',
      'available': 'Available',
      'unavailable': 'Unavailable',

      // Additional UI strings
      'bill_history': 'Bill History',
      'bill_summary': 'Bill Summary',
      'bill_to': 'Bill To',
      'bill_cancelled': 'Bill Cancelled',
      'bill_description': 'Bill Description',
      'clear': 'Clear',
      'clear_order': 'Clear Order',
      'clear_all': 'Clear All',
      'report': 'Report',
      'no_products_found': 'No products found',
      'product_not_found': 'Product not found',
      'max_stock_reached': 'Max stock reached! ({0} available)',
      'enter_quantity': 'Enter Quantity',
      'saved': 'Saved',
      'quotation': 'Quotation',
      'credit_notes': 'Credit Notes',
      'add_credit_note': 'Add Credit Note',
      'credit_details': 'Credit Details',
      'available_credit_notes': 'Available Credit Notes',
      'bill_wise': 'Bill Wise',
      'customer_details': 'Customer Details',
      'add_customer_details': 'Add Customer Details',
      'add_new_customer': 'Add New Customer',
      'customer_name': 'Customer Name',
      'customer_phone': 'Customer Phone',
      'payment_method': 'Payment Method',
      'cash_payment': 'Cash Payment',
      'online_payment': 'Online Payment',
      'credit_payment': 'Credit Payment',
      'split': 'Split',
      'received': 'Received',
      'due': 'Due',
      'advance': 'Advance',
      'internal_note': 'Internal Note',
      'add_internal_note': 'Add Internal Note',
      'add_note': 'Add Note',
      'discount_percent': 'Discount (%)',
      'discount_amount': 'Discount Amount',
      'price_with_tax': 'Price with Tax',
      'tax_amount': 'Tax Amount',
      'payment_details': 'Payment Details',
      'billing_details': 'Billing Details',
      'proceed': 'Proceed',
      'discard': 'Discard',
      'confirm': 'Confirm',
      'warning': 'Warning',
      'are_you_sure': 'Are you sure?',
      'cannot_be_undone': 'This action cannot be undone',
      'discard_bill': 'Discard Bill',
      'are_you_sure_discard': 'Are you sure you want to discard this bill?',
      'delete_product': 'Delete Product',
      'are_you_sure_delete_product': 'Are you sure you want to delete this product?',
      'item_name': 'Item Name',
      'hsn_code': 'HSN Code',
      'unit_price': 'Unit Price',
      'selling_price': 'Selling Price',
      'stock_enabled': 'Stock Enabled',
      'current_stock': 'Current Stock',
      'low_stock_alert': 'Low Stock Alert',
      'min_stock': 'Min Stock',
      'max_stock': 'Max Stock',
      'reorder_level': 'Reorder Level',
      'category_name': 'Category Name',
      'add_category_name': 'Add Category Name',
      'delete_category': 'Delete Category',
      'are_you_sure_delete_category': 'Are you sure you want to delete this category?',
      'edit_product': 'Edit Product',
      'edit_category': 'Edit Category',
      'save_product': 'Save Product',
      'save_category': 'Save Category',
      'required': 'Required',
      'invalid': 'Invalid',
      'enter_valid_value': 'Enter valid value',
      'expense_name': 'Expense Name',
      'expense_amount': 'Expense Amount',
      'expense_date': 'Expense Date',
      'expense_type': 'Expense Type',
      'add_expense_category': 'Add Expense Category',
      'expense_categories': 'Expense Categories',
      'staff_name': 'Staff Name',
      'staff_phone': 'Staff Phone',
      'staff_email': 'Staff Email',
      'staff_role': 'Staff Role',
      'permissions': 'Permissions',
      'grant_permissions': 'Grant Permissions',
      'role': 'Role',
      'admin': 'Admin',
      'staff': 'Staff',
      'cashier': 'Cashier',
      'manager': 'Manager',
      'add_new_staff': 'Add New Staff',
      'edit_staff': 'Edit Staff',
      'delete_staff': 'Delete Staff',
      'are_you_sure_delete_staff': 'Are you sure you want to delete this staff member?',
      'login': 'Login',
      'email_phone': 'Email / Phone',
      'password': 'Password',
      'forgot_password': 'Forgot Password',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'sign_in_with_google': 'Sign in with Google',
      'create_account': 'Create Account',
      'already_have_account': 'Already have an account?',
      'dont_have_account': 'Don\'t have an account?',
      'enter_email': 'Enter Email',
      'enter_phone': 'Enter Phone',
      'enter_password': 'Enter Password',
      'invalid_email': 'Invalid email',
      'invalid_phone': 'Invalid phone',
      'password_too_short': 'Password too short',
      'login_failed': 'Login failed',
      'signup_failed': 'Signup failed',
      'logout_confirm': 'Are you sure you want to logout?',
      'subscription_plan': 'Subscription Plan',
      'choose_plan': 'Choose Plan',
      'current_plan': 'Current Plan',
      'free_plan': 'Free Plan',
      'basic_plan': 'Basic Plan',
      'premium_plan': 'Premium Plan',
      'enterprise_plan': 'Enterprise Plan',
      'upgrade': 'Upgrade',
      'upgrade_now': 'Upgrade Now',
      'upgrade_to_premium': 'Upgrade to Premium',
      'features': 'Features',
      'per_month': 'Per Month',
      'per_year': 'Per Year',
      'best_value': 'Best Value',
      'most_popular': 'Most Popular',
      'contact_us': 'Contact Us',
      'terms_conditions': 'Terms & Conditions',
      'privacy_policy': 'Privacy Policy',
      'version': 'Version',
      'build': 'Build',
      'developed_by': 'Developed By',
      'powered_by': 'Powered By',
      'all_rights_reserved': 'All Rights Reserved',
      'language': 'Language',
      'currency': 'Currency',
      'timezone': 'Timezone',
      'notifications': 'Notifications',
      'enable_notifications': 'Enable Notifications',
      'sound': 'Sound',
      'vibration': 'Vibration',
      'backup': 'Backup',
      'restore': 'Restore',
      'backup_restore': 'Backup & Restore',
      'create_backup': 'Create Backup',
      'restore_backup': 'Restore Backup',
      'last_backup': 'Last Backup',
      'no_backup': 'No Backup',
      'backup_success': 'Backup successful',
      'restore_success': 'Restore successful',
      'backup_failed': 'Backup failed',
      'restore_failed': 'Restore failed',
      'analytics': 'Analytics',
      'dashboard': 'Dashboard',
      'overview': 'Overview',
      'statistics': 'Statistics',
      'charts': 'Charts',
      'graphs': 'Graphs',
      'top_products': 'Top Products',
      'top_customers': 'Top Customers',
      'top_categories': 'Top Categories',
      'recent_sales': 'Recent Sales',
      'recent_orders': 'Recent Orders',
      'pending_orders': 'Pending Orders',
      'completed_orders': 'Completed Orders',
      'cancelled_orders': 'Cancelled Orders',
      'total_sales': 'Total Sales',
      'total_revenue': 'Total Revenue',
      'total_profit': 'Total Profit',
      'total_orders': 'Total Orders',
      'total_customers': 'Total Customers',
      'total_products': 'Total Products',
      'income': 'Income',
      'expense': 'Expense',
      'profit': 'Profit',
      'loss': 'Loss',
      'revenue': 'Revenue',
      'growth': 'Growth',
      'decline': 'Decline',
      'percentage': 'Percentage',
      'change_from_last_month': 'Change from last month',
      'change_from_last_week': 'Change from last week',
      'last_7_days': 'Last 7 Days',
      'last_30_days': 'Last 30 Days',
      'last_90_days': 'Last 90 Days',
      'this_year': 'This Year',
      'last_year': 'Last Year',
      'custom_range': 'Custom Range',
      'start_date': 'Start Date',
      'end_date': 'End Date',
      'generate_report': 'Generate Report',
      'download_report': 'Download Report',
      'print_report': 'Print Report',
      'share_report': 'Share Report',
      'email_report': 'Email Report',
      'pdf_report': 'PDF Report',
      'excel_report': 'Excel Report',
      'report_generated': 'Report generated successfully',
      'report_failed': 'Report generation failed',
      'no_data': 'No data available',
      'no_results': 'No results found',
      'try_again': 'Try Again',
      'retry': 'Retry',
      'reload': 'Reload',
      'something_went_wrong': 'Something went wrong',
      'network_error': 'Network error',
      'server_error': 'Server error',
      'connection_failed': 'Connection failed',
      'please_check_internet': 'Please check your internet connection',
      'offline': 'Offline',
      'connecting': 'Connecting...',
      'syncing': 'Syncing...',
      'sync_failed': 'Sync failed',
      'sync_success': 'Synced successfully',
      'last_synced': 'Last synced',
      'never_synced': 'Never synced',
      'sync_now': 'Sync Now',
      'auto_sync': 'Auto Sync',
      'manual_sync': 'Manual Sync',
      'sync_settings': 'Sync Settings',
      'data_usage': 'Data Usage',
      'storage': 'Storage',
      'clear_cache': 'Clear Cache',
      'clear_data': 'Clear Data',
      'cache_cleared': 'Cache cleared',
      'data_cleared': 'Data cleared',
      'confirm_clear': 'Are you sure you want to clear?',
      'scanning': 'Scanning...',
      'scan_barcode': 'Scan Barcode',
      'scan_qr': 'Scan QR Code',
      'camera_permission': 'Camera Permission',
      'camera_permission_required': 'Camera permission is required',
      'grant_permission': 'Grant Permission',
      'permission_denied': 'Permission Denied',
      'enable_from_settings': 'Enable from Settings',
      'printer_not_found': 'Printer not found',
      'printer_connected': 'Printer connected',
      'printer_disconnected': 'Printer disconnected',
      'connecting_printer': 'Connecting to printer...',
      'print_settings': 'Print Settings',
      'paper_size': 'Paper Size',
      'print_quality': 'Print Quality',
      'copies': 'Copies',
      'print_preview': 'Print Preview',
      'printing': 'Printing...',
      'print_success': 'Printed successfully',
      'print_failed': 'Print failed',
      'bluetooth': 'Bluetooth',
      'wifi': 'WiFi',
      'usb': 'USB',
      'network': 'Network',
      'select_printer': 'Select Printer',
      'add_printer': 'Add Printer',
      'remove_printer': 'Remove Printer',
      'test_print': 'Test Print',
      'invoice_number': 'Invoice Number',
      'bill_number': 'Bill Number',
      'order_number': 'Order Number',
      'reference_number': 'Reference Number',
      'transaction_id': 'Transaction ID',
      'payment_id': 'Payment ID',
      'receipt_number': 'Receipt Number',
      'customer_copy': 'Customer Copy',
      'merchant_copy': 'Merchant Copy',
      'thank_you': 'Thank You',
      'visit_again': 'Visit Again',
      'terms': 'Terms',
      'signature': 'Signature',
      'authorized_signature': 'Authorized Signature',
      'stamp': 'Stamp',
      'company_stamp': 'Company Stamp',
      'powered_by_maxbillup': 'Powered by MaxBillUp',
      'generated_by': 'Generated By',
      'page': 'Page',
      'of': 'of',
      'sub_total': 'Sub Total',
      'taxable_amount': 'Taxable Amount',
      'tax_details': 'Tax Details',
      'round_off': 'Round Off',
      'net_amount': 'Net Amount',
      'amount_in_words': 'Amount in Words',
      'rupees': 'Rupees',
      'only': 'Only',
      'payment_status': 'Payment Status',
      'paid_amount': 'Paid Amount',
      'remaining_amount': 'Remaining Amount',
      'change_return': 'Change Return',
      'no_change': 'No Change',
      'payment_type': 'Payment Type',
      'card': 'Card',
      'upi': 'UPI',
      'wallet': 'Wallet',
      'cheque': 'Cheque',
      'bank_transfer': 'Bank Transfer',
      'other': 'Other',
      'specify': 'Specify',

      // Menu.dart specific keys
      'billhistory': 'Bill History',
      'nobillsfound': 'No bills found',
      'settle_bill': 'Settle Bill',
      'by': 'By',
      'bill_not_found': 'Bill not found or deleted.',
      'created_by': 'Created by',
      'issued_on': 'Issued on',
      'invoice_items': 'Invoice items',
      'totalitems': 'Total items',
      'totalquantity': 'Total Qty',
      'totalamount': 'Total Amount',
      'refund': 'Refund',
      'preparing_print': 'Preparing print...',
      'printfailed': 'Print failed',
      'creditdetails': 'Credit Details',
      'creditnote': 'Credit Note',
      'no_sales_credits': 'No sales credits found',
      'no_matching_customers': 'No matching customers found',
      'total_sales_credit': 'Total Sales Credit',
      'no_purchase_credits': 'No purchase credits found',
      'no_matching_purchase_credits': 'No matching purchase credits',
      'total_purchase_credit': 'Total Purchase Credit',
      'unknown_supplier': 'Unknown Supplier',
      'purchase_credit_note': 'Purchase Credit Note',
      'credit_note_not_found': 'Credit note not found',
      'areyousure': 'Are you sure?',
      'mode': 'Mode',
      'addnewcustomer': 'Add New Customer',
      'existing_customer': 'Existing Customer',
      'name_phone_required': 'Please enter name and phone number',
      'no_customers_found': 'No customers found',
      'staffmanagement': 'Staff Management',
      'addnewstaff': 'Add New Staff',
      'savestaff': 'Save Staff',
      'staff_added_success': 'Staff added successfully',
      'sale_return': 'Sale Return',
      'thismonth': 'This Month',
      'lastmonth': 'Last Month',
      'invoicenumber': 'Invoice No.',
      'customerdetails': 'Customer Details',
      'cancel_bill': 'Cancel Bill',
      'enter_valid_amount': 'Please enter a valid amount',
      'payment_settled': 'Payment settled successfully',
      'payment_recorded': 'Payment recorded',
      'error_processing_payment': 'Error processing payment',
      'add_discount': 'Add Discount',
      'enter_note': 'Enter note...',
      'bill_updated_success': 'Bill updated successfully',
      'error_updating_bill': 'Error updating bill',

      // Reports page keys (unique additions)
      'analytics_overview': 'Analytics & Overview',
      'daybook_today': 'DayBook (Today)',
      'sales_transactions': 'Sales & Transactions',
      'item_sales_report': 'Item Sales Report',
      'inventory_products': 'Inventory & Products',
      'low_stock_products': 'Low Stock Products',
      'financials_tax': 'Financials & Tax',
      'hsn_report': 'HSN Report',
      'staff_sale_report': 'Staff Sale Report',
      'no_report_access': 'No Report Access',
      'no_report_permission_msg': 'You don\'t have permission to view any reports. Contact your administrator.',
      'hour': 'Hour',
      'currency_symbol': '₹',

      // Expenses page keys (unique additions)
      'new_expense': 'New Expense',
      'expense_details': 'Expense Details',
      'new_other_expense': 'New Other Expense',

      // Stock purchase keys (unique additions)
      'new_stock_purchase': 'New Stock Purchase',
      'purchase_details': 'Purchase Details',

      // Products page keys (unique additions)
      'filter_by_stock': 'Filter By Stock',
      'all_products': 'All Products',
      'low_stock_filter': 'Low Stock (< 10)',
      'remove': 'Remove',
      'enter_valid_quantity': 'Please enter a valid quantity',

      // Category keys (unique additions)
      'category_updated_success': 'Category updated successfully',
      'category_deleted_success': 'Category deleted successfully',
      'are_you_sure_delete': 'Are you sure you want to delete',

      // AddProduct keys (unique additions)
      'add_new_unit': 'Add New Unit',

      // Profile/Settings keys (unique additions)
      'upgrade_plan': 'Upgrade Plan',
      'restricted_access': 'Restricted Access',

      // Login keys (unique additions)
      'welcome_to': 'Welcome to',

      // Bill keys (unique additions)
      'total_payable': 'Total Payable',
      'new_customer': 'New Customer',
      'select_customer': 'Select Customer',
      'total_bill_amount': 'Total Bill Amount',
      'paid_so_far': 'Paid So Far',
      'total_bill': 'Total Bill',

      // Quotation keys (unique additions)
      'share_error': 'Share Error',
      'no_printer_selected': 'No Printer Selected',
      'select_printer_from_settings': 'Please select a printer from Settings > Printer Setup before printing.',
      'print_error': 'Print Error',

      // TaxSettings keys (unique additions)
      'create_type': 'Create Type',
      'add_tax_rate': 'Add Tax Rate',
      'update_settings': 'Update Settings',

      // StaffManagement keys (unique additions)
      'no_staff_members': 'No staff members yet',
      'invite_to_start': 'Invite someone to get started',
      'invite_new_staff': 'Invite New Staff',
      'send_invite': 'Send Invite',
      'edit_staff_member': 'Edit Staff Member',
      'remove_staff': 'Remove Staff',

      // QuotationsList keys (unique additions)
      'no_quotations_found': 'No quotations found',
      'date_newest_first': 'Date: Newest First',
      'date_oldest_first': 'Date: Oldest First',
      'amount_high_to_low': 'Amount: High to Low',
      'amount_low_to_high': 'Amount: Low to High',
      'settled': 'Settled',

      // Additional common keys (unique additions)
      'fill_required_fields': 'Please fill in required fields',
      'expense_saved_success': 'Expense saved successfully',
      'enter_category_name': 'Please enter a category name',
      'category_added_success': 'Category added successfully',
      'category_exists': 'Category already exists',

      // Saved orders keys (unique additions)
      'order_deleted': 'Order deleted',
      'delete_order': 'Delete Order',
      'no_saved_orders': 'No Saved Orders',

      // BusinessDetailsPage keys
      'complete_profile_title': 'Complete Your Profile',
      'complete_profile_subtitle': 'Please provide your business details to get started',
      'personaldetails': 'Personal Details',
      'your_name': 'Your Name',
      'enter_full_name': 'Enter your full name',
      'name_required': 'Name is required',
      'your_phone': 'Your Phone Number',
      'phone_required': 'Phone is required',
      'phone_invalid_10_digit': 'Enter valid 10-digit phone',
      'businessdetails': 'Business Details',
      'businessname': 'Business Name',
      'enter_business_name': 'Enter your business name',
      'business_name_required': 'Business name is required',
      'businessphone': 'Business Phone Number',
      'enter_business_phone': 'Enter business phone number',
      'business_phone_required': 'Business phone is required',
      'gstin_optional': 'GSTIN (Optional)',
      'enter_gstin': 'Enter GSTIN number',
      'businesslocation': 'Business Location',
      'enter_business_location': 'Enter your business location',
      'business_location_required': 'Business location is required',
      'complete_registration': 'Complete Registration',
      'business_registered_success': 'Business registered successfully!',
      'failed_to_save': 'Failed to save',

      // SubscriptionPlanPage keys
      'subscription_expiry': 'Expires',
      'permonth': '/month',
      'six_months': '6 Months',
      'peryear': '/year',
      'save_20': 'SAVE 20%',
      'perperiod': '/period',
      'full_feature_comparison': 'Full Feature Comparison',
      'freeplan': 'Free',
      'bulk_inventory': 'Bulk Inventory',
      'logo_on_bill': 'Logo on Bill',
      'customer_credit': 'Customer Credit',
      'edit_bill': 'Edit Bill',
      'taxreport': 'Tax Report',
      'import_contacts': 'Import Contacts',
      'pos_billing': 'POS Billing',
      'cloud_storage': 'Cloud Storage',
      'currentplan': 'Current Plan',
      'pay_now': 'Pay Now',
      'paymentsuccessful': 'Payment Successful! Plan Upgraded.',
      'paymentfailed': 'Payment Failed',

      // BarcodeScanner keys
      'scanbarcode': 'Scan Barcode',
      'product_added_scanned': 'Product added',
      'total_scanned': 'Total scanned',
      'products_scanned': 'Products Scanned',
      'scan_multiple_products': 'Scan multiple products\nPress back when done',

      // Language settings keys
      'available_languages': 'Available Languages',
      'language_changed_to': 'Language changed to',
      'common_translations': 'Common Translations',

      // Additional keys
      'nodata': 'No data available',
      'daybook': 'DayBook',
      'sales_summary': 'Sales Summary',
      'customername': 'Customer Name',
      'customerphone': 'Customer Phone',

      // AddProduct page localization keys
      'item_information': 'आइटम जानकारी',
      'item_name': 'आइटम का नाम',
      'leave_blank_for_price': 'बिक्री के समय मूल्य के लिए खाली छोड़ें।',
      'more_details': 'अधिक विवरण',
      'cost_price_optional': 'लागत मूल्य (वैकल्पिक)',
      'mrp_optional': 'एम.आर.पी (वैकल्पिक)',
      'product_code': 'उत्पाद कोड',
      'generate': 'जनरेट करें',
      'find': 'खोजें',
      'hsn_scn': 'एचएसएन/एससीएन',
      'barcode_info': 'बाहरी बारकोड रीडर से बारकोड जोड़ने के लिए, बारकोड फ़ील्ड पर टैप करें और बारकोड स्कैन करें',
      'unit': 'इकाई',
      'stock_unit': 'स्टॉक इकाई',
      'this_field_is_required': 'यह फ़ील्ड आवश्यक है',

      // Category.dart specific keys
      'search_categories': 'वगைகளைத் தேடு...',
      'no_categories_yet': 'இன்னும் வகைகள் இல்லை',
      'add_first_category': 'பொருட்களை ஒழுங்குபடுத்த உங்கள் முதல் வகையைச் சேர்க்கவும்',
      'no_categories_found': 'வகைகள் எதுவும் இல்லை',
      'try_searching_keywords': 'வேறு சொற்களுடன் தேட முயற்சிக்கவும்',
      'edit': 'திருத்து',
      'add_product': 'பொருள் சேர்',
      'create_new_product': 'புதிய பொருள் உருவாக்கு',
      'add_existing_product': 'ஏற்கனவே உள்ள பொருளை சேர்',
      'no_products_available': 'பொருட்கள் எதுவும் இல்லை',
      'current': 'தற்போது',
      'price_on_sale': 'விற்பனை விலை',
      'added_to': 'சேர்க்கப்பட்டது',
    },

    'hi': {
      // Common
      'app_name': 'मैक्सबिलअप',
      'welcome': 'स्वागत है',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'add': 'जोड़ें',
      'update': 'अपडेट करें',
      'search': 'खोजें',
      'settings': 'सेटिंग्स',
      'logout': 'लॉग आउट',
      'yes': 'हां',
      'no': 'नहीं',
      'ok': 'ठीक है',
      'done': 'हो गया',
      'loading': 'लोड हो रहा है...',
      'coming_soon': 'जल्द आ रहा है',
      'used': 'उपयोग किया गया',
      'paid_amount': 'भुगतान राशि',
      'invoice_items': 'चालान आइटम',
      'bill_not_found': 'बिल नहीं मिला या हटा दिया गया',
      'created_by': 'द्वारा बनाया गया',
      'issued_on': 'जारी किया गया',
      'totalquantity': 'कुल मात्रा',
      'invoice': 'चालान',
      'by': 'द्वारा',
      'error': 'त्रुटि',
      'success': 'सफलता',

      // Navigation
      'home': 'होम',
      'sales': 'बिक्री',
      'stocks': 'स्टॉक',
      'reports': 'रिपोर्ट',
      'menu': 'मेनू',

      // Sales
      'new_sale': 'नई बिक्री',
      'sale_all': 'सभी बिक्री',
      'quick_sale': 'त्वरित बिक्री',
      'saved_orders': 'सहेजे गए आदेश',
      'complete_payment': 'भुगतान पूरा करें',
      'add_to_cart': 'कार्ट में जोड़ें',
      'cart': 'कार्ट',
      'checkout': 'चेकआउट',
      'payment_mode': 'भुगतान मोड',
      'cash': 'नकद',
      'online': 'ऑनलाइन',
      'credit': 'उधार',
      'split_payment': 'विभाजित भुगतान',

      // Bill
      'subtotal': 'उप-योग',
      'discount': 'छूट',
      'tax': 'कर',
      'total': 'कुल',
      'grand_total': 'कुल योग',
      'amount_received': 'प्राप्त राशि',
      'change': 'बदलाव',
      'customer': 'ग्राहक',
      'add_customer': 'ग्राहक जोड़ें',

      // Products/Stocks
      'products': 'उत्पाद',
      'category': 'श्रेणी',
      'addproduct': 'उत्पाद जोड़ें',
      'price': 'मूल्य',
      'cost_price': 'लागत मूल्य',
      'mrp': 'एम.आर.पी',
      'quantity': 'मात्रा',
      'barcode': 'बारकोड',
      'stock': 'स्टॉक',
      'in_stock': 'स्टॉक में',
      'out_of_stock': 'स्टॉक खत्म',
      'low_stock': 'कम स्टॉक',

      // Tax
      'tax_settings': 'कर सेटिंग्स',
      'add_tax': 'कर जोड़ें',
      'tax_name': 'कर का नाम',
      'tax_percentage': 'कर %',
      'price_includes_tax': 'मूल्य में कर शामिल',
      'price_without_tax': 'मूल्य कर रहित',
      'zero_rated_tax': 'शून्य दर कर',
      'exempt_tax': 'कर मुक्त',

      // Settings
      'profile': 'प्रोफ़ाइल',
      'business_details': 'व्यापार विवरण',
      'business_name': 'व्यापार का नाम',
      'business_phone': 'व्यापार फोन',
      'business_location': 'व्यापार स्थान',
      'business_email': 'व्यापार ईमेल',
      'gstin': 'जीएसटीआईएन',
      'choose_language': 'भाषा चुनें',
      'theme': 'थीम',
      'printer_setup': 'प्रिंटर सेटअप',
      'receipt_customization': 'रसीद अनुकूलन',
      'feature_settings': 'फीचर सेटिंग्स',
      'help': 'मदद',
      'about': 'के बारे में',

      // Reports
      'daily_report': 'दैनिक रिपोर्ट',
      'monthly_report': 'मासिक रिपोर्ट',
      'sales_report': 'बिक्री रिपोर्ट',
      'stock_report': 'स्टॉक रिपोर्ट',
      'tax_report': 'कर रिपोर्ट',
      'profit_loss': 'लाभ और हानि',

      // Messages
      'product_added': 'उत्पाद सफलतापूर्वक जोड़ा गया',
      'product_updated': 'उत्पाद अपडेट किया गया',
      'product_deleted': 'उत्पाद हटाया गया',
      'sale_completed': 'बिक्री पूर्ण हुई',
      'payment_successful': 'भुगतान सफल',
      'payment_failed': 'भुगतान विफल',
      'no_items_in_cart': 'कार्ट में कोई आइटम नहीं',
      'invalid_input': 'अमान्य इनपुट',
      'required_field': 'यह फ़ील्ड आवश्यक है',
      'confirm_delete': 'क्या आप वाकई हटाना चाहते हैं?',
      'saved_offline': 'ऑफ़लाइन सहेजा गया। ऑनलाइन होने पर सिंक होगा।',
      'sync_completed': 'सिंक पूर्ण हुआ',

      // Additional Pages
      'quotations': 'कोटेशन',
      'create_quotation': 'कोटेशन बनाएं',
      'quotation_list': 'कोटेशन सूची',
      'convert_to_sale': 'बिक्री में बदलें',
      'expenses': 'खर्चे',
      'other_expenses': 'अन्य खर्चे',
      'add_expense': 'खर्च जोड़ें',
      'expense_category': 'खर्च श्रेणी',
      'categories': 'श्रेणियाँ',
      'add_category': 'श्रेणी जोड़ें',
      'staff_management': 'स्टाफ प्रबंधन',
      'add_staff': 'स्टाफ जोड़ें',
      'customers': 'ग्राहक',
      'supplier': 'आपूर्तिकर्ता',
      'purchase': 'खरीदी',
      'stock_purchase': 'स्टॉक खरीदी',
      'view': 'देखें',
      'print': 'प्रिंट करें',
      'share': 'साझा करें',
      'receipt': 'रसीद',
      'date': 'तारीख',
      'time': 'समय',
      'from': 'से',
      'to': 'तक',
      'all': 'सभी',
      'today': 'आज',
      'yesterday': 'कल',
      'this_week': 'इस सप्ताह',
      'this_month': 'इस महीने',
      'custom': 'कस्टम',
      'apply': 'लागू करें',
      'reset': 'रीसेट करें',
      'export': 'निर्यात करें',
      'download': 'डाउनलोड करें',
      'upload': 'अपलोड करें',
      'back': 'वापस',
      'next': 'अगला',
      'previous': 'पिछला',
      'finish': 'समाप्त',
      'skip': 'छोड़ें',
      'continue': 'जारी रखें',
      'close': 'बंद करें',
      'open': 'खोलें',
      'refresh': 'ताज़ा करें',
      'sync': 'सिंक करें',
      'online_mode': 'ऑनलाइन मोड',
      'offline_mode': 'ऑफ़लाइन मोड',
      'select': 'चुनें',
      'select_all': 'सभी चुनें',
      'deselect_all': 'सभी अचयनित करें',
      'filter': 'फ़िल्टर',
      'sort': 'क्रमबद्ध करें',
      'ascending': 'बढ़ते क्रम में',
      'descending': 'घटते क्रम में',
      'name': 'नाम',
      'description': 'विवरण',
      'amount': 'राशि',
      'paid': 'भुगतान किया',
      'unpaid': 'अवैतनिक',
      'pending': 'लंबित',
      'completed': 'पूर्ण',
      'cancelled': 'रद्द',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'enabled': 'सक्षम',
      'disabled': 'अक्षम',
      'phone': 'फोन',
      'email': 'ईमेल',
      'address': 'पता',
      'city': 'शहर',
      'state': 'राज्य',
      'country': 'देश',
      'pincode': 'पिनकोड',
      'notes': 'नोट्स',
      'remarks': 'टिप्पणी',
      'status': 'स्थिति',
      'action': 'कार्रवाई',
      'actions': 'कार्रवाईयाँ',
      'details': 'विवरण',
      'summary': 'सारांश',
      'billing': 'बिलिंग',
      'shipping': 'शिपिंग',
      'payment': 'भुगतान',
      'order': 'आदेश',
      'orders': 'आदेश',
      'item': 'आइटम',
      'items': 'आइटम',
      'unit': 'इकाई',
      'rate': 'दर',
      'gst': 'जीएसटी',
      'vat': 'वैट',
      'cgst': 'सीजीएसटी',
      'sgst': 'एसजीएसटी',
      'igst': 'आईजीएसटी',
      'total_items': 'कुल आइटम',
      'total_amount': 'कुल राशि',
      'due_amount': 'बकाया राशि',
      'balance': 'शेष',
      'credit_limit': 'क्रेडिट सीमा',
      'available': 'उपलब्ध',
      'unavailable': 'अनुपलब्ध',

      // Additional UI strings
      'bill_history': 'बिल इतिहास',
      'bill_summary': 'बिल सारांश',
      'bill_to': 'बिल प्राप्तकर्ता',
      'bill_cancelled': 'बिल रद्द',
      'bill_description': 'बिल विवरण',
      'clear': 'साफ़ करें',
      'clear_order': 'ऑर्डर साफ़ करें',
      'clear_all': 'सभी साफ़ करें',
      'report': 'रिपोर्ट',
      'no_products_found': 'कोई उत्पाद नहीं मिला',
      'product_not_found': 'उत्पाद नहीं मिला',
      'max_stock_reached': 'अधिकतम स्टॉक सीमा! ({0} उपलब्ध)',
      'enter_quantity': 'मात्रा दर्ज करें',
      'saved': 'सहेजा गया',
      'quotation': 'कोटेशन',
      'credit_notes': 'क्रेडिट नोट्स',
      'add_credit_note': 'क्रेडिट नोट जोड़ें',
      'credit_details': 'क्रेडिट विवरण',
      'available_credit_notes': 'उपलब्ध क्रेडिट नोट्स',
      'bill_wise': 'बिल अनुसार',
      'customer_details': 'ग्राहक विवरण',
      'add_customer_details': 'ग्राहक विवरण जोड़ें',
      'add_new_customer': 'नया ग्राहक जोड़ें',
      'customer_name': 'ग्राहक का नाम',
      'customer_phone': 'ग्राहक फोन',
      'payment_method': 'भुगतान विधि',
      'cash_payment': 'नकद भुगतान',
      'online_payment': 'ऑनलाइन भुगतान',
      'credit_payment': 'उधार भुगतान',
      'split': 'विभाजित',
      'received': 'प्राप्त',
      'due': 'बकाया',
      'advance': 'अग्रिम',
      'internal_note': 'आंतरिक नोट',
      'add_internal_note': 'आंतरिक नोट जोड़ें',
      'add_note': 'नोट जोड़ें',
      'discount_percent': 'छूट (%)',
      'discount_amount': 'छूट राशि',
      'price_with_tax': 'कर सहित मूल्य',
      'tax_amount': 'कर राशि',
      'payment_details': 'भुगतान विवरण',
      'billing_details': 'बिलिंग विवरण',
      'proceed': 'आगे बढ़ें',
      'discard': 'छोड़ें',
      'confirm': 'पुष्टि करें',
      'warning': 'चेतावनी',
      'are_you_sure': 'क्या आप निश्चित हैं?',
      'cannot_be_undone': 'यह क्रिया पूर्ववत नहीं की जा सकती',
      'discard_bill': 'बिल छोड़ें',
      'are_you_sure_discard': 'क्या आप वाकई इस बिल को छोड़ना चाहते हैं?',
      'delete_product': 'उत्पाद हटाएं',
      'are_you_sure_delete_product': 'क्या आप वाकई इस उत्पाद को हटाना चाहते हैं?',
      'item_name': 'आइटम का नाम',
      'hsn_code': 'एचएसएन कोड',
      'unit_price': 'इकाई मूल्य',
      'selling_price': 'विक्रय मूल्य',
      'stock_enabled': 'स्टॉक सक्षम',
      'current_stock': 'वर्तमान स्टॉक',
      'low_stock_alert': 'कम स्टॉक अलर्ट',
      'min_stock': 'न्यूनतम स्टॉक',
      'max_stock': 'अधिकतम स्टॉक',
      'reorder_level': 'पुनः ऑर्डर स्तर',
      'category_name': 'श्रेणी नाम',
      'add_category_name': 'श्रेणी नाम जोड़ें',
      'delete_category': 'श्रेणी हटाएं',
      'are_you_sure_delete_category': 'क्या आप वाकई इस श्रेणी को हटाना चाहते हैं?',
      'edit_product': 'उत्पाद संपादित करें',
      'edit_category': 'श्रेणी संपादित करें',
      'save_product': 'उत्पाद सहेजें',
      'save_category': 'श्रेणी सहेजें',
      'required': 'आवश्यक',
      'invalid': 'अमान्य',
      'enter_valid_value': 'मान्य मान दर्ज करें',
      'expense_name': 'खर्च का नाम',
      'expense_amount': 'खर्च राशि',
      'expense_date': 'खर्च तिथि',
      'expense_type': 'खर्च प्रकार',
      'add_expense_category': 'खर्च श्रेणी जोड़ें',
      'expense_categories': 'खर्च श्रेणियां',
      'staff_name': 'स्टाफ का नाम',
      'staff_phone': 'स्टाफ फोन',
      'staff_email': 'स्टाफ ईमेल',
      'staff_role': 'स्टाफ भूमिका',
      'permissions': 'अनुमतियां',
      'grant_permissions': 'अनुमतियां दें',
      'role': 'भूमिका',
      'admin': 'व्यवस्थापक',
      'staff': 'स्टाफ',
      'cashier': 'कैशियर',
      'manager': 'प्रबंधक',
      'add_new_staff': 'नया स्टाफ जोड़ें',
      'edit_staff': 'स्टाफ संपादित करें',
      'delete_staff': 'स्टाफ हटाएं',
      'are_you_sure_delete_staff': 'क्या आप वाकई इस स्टाफ सदस्य को हटाना चाहते हैं?',
      'login': 'लॉगिन',
      'email_phone': 'ईमेल / फोन',
      'password': 'पासवर्ड',
      'forgot_password': 'पासवर्ड भूल गए',
      'sign_in': 'साइन इन',
      'sign_up': 'साइन अप',
      'sign_in_with_google': 'Google से साइन इन करें',
      'create_account': 'खाता बनाएं',
      'already_have_account': 'पहले से खाता है?',
      'dont_have_account': 'खाता नहीं है?',
      'enter_email': 'ईमेल दर्ज करें',
      'enter_phone': 'फोन दर्ज करें',
      'enter_password': 'पासवर्ड दर्ज करें',
      'invalid_email': 'अमान्य ईमेल',
      'invalid_phone': 'अमान्य फोन',
      'password_too_short': 'पासवर्ड बहुत छोटा',
      'login_failed': 'उलॉगिन विफल',
      'signup_failed': 'साइनअप विफल',
      'logout_confirm': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'subscription_plan': 'सब्सक्रिप्शन प्लान',
      'choose_plan': 'प्लान चुनें',
      'current_plan': 'वर्तमान प्लान',
      'free_plan': 'मुफ्त प्लान',
      'basic_plan': 'बेसिक प्लान',
      'premium_plan': 'प्रीमियम प्लान',
      'enterprise_plan': 'एंटरप्राइज प्लान',
      'upgrade': 'अपग्रेड',
      'upgrade_now': 'अभी अपग्रेड करें',
      'upgrade_to_premium': 'प्रीमियम में अपग्रेड करें',
      'features': 'विशेषताएं',
      'per_month': 'प्रति माह',
      'per_year': 'प्रति वर्ष',
      'best_value': 'सर्वोत्तम मूल्य',
      'most_popular': 'सबसे लोकप्रिय',
      'contact_us': 'संपर्क करें',
      'terms_conditions': 'नियम और शर्तें',
      'privacy_policy': 'गोपनीयता नीति',
      'version': 'संस्करण',
      'build': 'बिल्ड',
      'developed_by': 'द्वारा विकसित',
      'powered_by': 'द्वारा संचालित',
      'all_rights_reserved': 'सर्वाधिकार सुरक्षित',
      'language': 'भाषा',
      'currency': 'मुद्रा',
      'timezone': 'समय क्षेत्र',
      'notifications': 'सूचनाएं',
      'enable_notifications': 'सूचनाएं सक्षम करें',
      'sound': 'ध्वनि',
      'vibration': 'कंपन',
      'backup': 'बैकअप',
      'restore': 'पुनर्स्थापित',
      'backup_restore': 'बैकअप और पुनर्स्थापना',
      'create_backup': 'बैकअप बनाएं',
      'restore_backup': 'बैकअप पुनर्स्थापित करें',
      'last_backup': 'अंतिम बैकअप',
      'no_backup': 'कोई बैकअप नहीं',
      'backup_success': 'बैकअप सफल',
      'restore_success': 'पुनर्स्थापना सफल',
      'backup_failed': 'बैकअप विफल',
      'restore_failed': 'पुनर्स्थापना विफल',
      'analytics': 'विश्लेषण',
      'dashboard': 'डैशबोर्ड',
      'overview': 'अवलोकन',
      'statistics': 'सांख्यिकी',
      'charts': 'चार्ट',
      'graphs': 'ग्राफ',
      'top_products': 'शीर्ष उत्पाद',
      'top_customers': 'शीर्ष ग्राहक',
      'top_categories': 'शीर्ष श्रेणियां',
      'recent_sales': 'हालिया बिक्री',
      'recent_orders': 'हालिया ऑर्डर',
      'pending_orders': 'लंबित ऑर्डर',
      'completed_orders': 'पूर्ण ऑर्डर',
      'cancelled_orders': 'रद्द ऑर्डर',
      'total_sales': 'कुल बिक्री',
      'total_revenue': 'कुल राजस्व',
      'total_profit': 'कुल लाभ',
      'total_orders': 'कुल ऑर्डर',
      'total_customers': 'कुल ग्राहक',
      'total_products': 'कुल उत्पाद',
      'income': 'आय',
      'expense': 'व्यय',
      'profit': 'लाभ',
      'loss': 'हानि',
      'revenue': 'राजस्व',
      'growth': 'वृद्धि',
      'decline': 'गिरावट',
      'percentage': 'प्रतिशत',
      'change_from_last_month': 'पिछले महीने से परिवर्तन',
      'change_from_last_week': 'पिछले सप्ताह से परिवर्तन',
      'last_7_days': 'पिछले 7 दिन',
      'last_30_days': 'पिछले 30 दिन',
      'last_90_days': 'पिछले 90 दिन',
      'this_year': 'इस वर्ष',
      'last_year': 'पिछले वर्ष',
      'custom_range': 'कस्टम रेंज',
      'start_date': 'प्रारंभ तिथि',
      'end_date': 'समाप्ति तिथि',
      'generate_report': 'रिपोर्ट बनाएं',
      'download_report': 'रिपोर्ट डाउनलोड करें',
      'print_report': 'रिपोर्ट प्रिंट करें',
      'share_report': 'रिपोर्ट साझा करें',
      'email_report': 'रिपोर्ट ईमेल करें',
      'pdf_report': 'पीडीएफ रिपोर्ट',
      'excel_report': 'एक्सेल रिपोर्ट',
      'report_generated': 'रिपोर्ट सफलतापूर्वक बनाई गई',
      'report_failed': 'रिपोर्ट बनाना विफल',
      'no_data': 'कोई डेटा उपलब्ध नहीं',
      'no_results': 'कोई परिणाम नहीं मिला',
      'try_again': 'पुनः प्रयास करें',
      'retry': 'पुनः प्रयास',
      'reload': 'पुनः लोड करें',
      'something_went_wrong': 'कुछ गलत हो गया',
      'network_error': 'नेटवर्क त्रुटि',
      'server_error': 'सर्वर त्रुटि',
      'connection_failed': 'कनेक्शन विफल',
      'please_check_internet': 'कृपया अपना इंटरनेट कनेक्शन जांचें',
      'offline': 'ऑफ़लाइन',
      'connecting': 'कनेक्ट हो रहा है...',
      'syncing': 'सिंक हो रहा है...',
      'sync_failed': 'सिंक विफल',
      'sync_success': 'सफलतापूर्वक सिंक किया गया',
      'last_synced': 'अंतिम सिंक',
      'never_synced': 'कभी सिंक नहीं किया गया',
      'sync_now': 'अभी सिंक करें',
      'auto_sync': 'ऑटो सिंक',
      'manual_sync': 'मैनुअल सिंक',
      'sync_settings': 'सिंक सेटिंग्स',
      'data_usage': 'डेटा उपयोग',
      'storage': 'स्टोरेज',
      'clear_cache': 'कैश साफ़ करें',
      'clear_data': 'डेटा साफ़ करें',
      'cache_cleared': 'कैश साफ़ किया गया',
      'data_cleared': 'डेटा साफ़ किया गया',
      'confirm_clear': 'क्या आप वाकई साफ़ करना चाहते हैं?',
      'scanning': 'स्कैन हो रहा है...',
      'scan_barcode': 'बारकोड स्कैन करें',
      'scan_qr': 'QR कोड स्कैन करें',
      'camera_permission': 'कैमरा अनुमति',
      'camera_permission_required': 'कैमरा अनुमति आवश्यक है',
      'grant_permission': 'अनुमति दें',
      'permission_denied': 'अनुमति अस्वीकृत',
      'enable_from_settings': 'सेटिंग्स से सक्षम करें',
      'printer_not_found': 'प्रिंटर नहीं मिला',
      'printer_connected': 'प्रिंटर कनेक्ट हुआ',
      'printer_disconnected': 'प्रिंटर डिस्कनेक्ट हुआ',
      'connecting_printer': 'प्रिंटर से कनेक्ट हो रहा है...',
      'print_settings': 'प्रिंट सेटिंग्स',
      'paper_size': 'पेपर साइज़',
      'print_quality': 'प्रिंट गुणवत्ता',
      'copies': 'प्रतियां',
      'print_preview': 'प्रिंट पूर्वावलोकन',
      'printing': 'प्रिंट हो रहा है...',
      'print_success': 'सफलतापूर्वक प्रिंट किया गया',
      'print_failed': 'प्रिंट विफल',
      'bluetooth': 'ब्लूटूथ',
      'wifi': 'वाईफाई',
      'usb': 'यूएसबी',
      'network': 'नेटवर्क',
      'select_printer': 'प्रिंटर चुनें',
      'add_printer': 'प्रिंटर जोड़ें',
      'remove_printer': 'प्रिंटर हटाएं',
      'test_print': 'टेस्ट प्रिंट',
      'invoice_number': 'चालान संख्या',
      'bill_number': 'बिल संख्या',
      'order_number': 'ऑर्डर संख्या',
      'reference_number': 'संदर्भ संख्या',
      'transaction_id': 'लेनदेन आईडी',
      'payment_id': 'भुगतान आईडी',
      'receipt_number': 'रसीद संख्या',
      'customer_copy': 'ग्राहक प्रति',
      'merchant_copy': 'व्यापारी प्रति',
      'thank_you': 'धन्यवाद',
      'visit_again': 'फिर आएं',
      'terms': 'शर्तें',
      'signature': 'हस्ताक्षर',
      'authorized_signature': 'अधिकृत हस्ताक्षर',
      'stamp': 'मुहर',
      'company_stamp': 'कंपनी मुहर',
      'powered_by_maxbillup': 'MaxBillUp द्वारा संचालित',
      'generated_by': 'द्वारा बनाया गया',
      'page': 'पृष्ठ',
      'of': 'का',
      'sub_total': 'उप योग',
      'taxable_amount': 'कर योग्य राशि',
      'tax_details': 'कर विवरण',
      'round_off': 'राउंड ऑफ',
      'net_amount': 'शुद्ध राशि',
      'amount_in_words': 'शब्दों में राशि',
      'rupees': 'रुपये',
      'only': 'मात्र',
      'payment_status': 'भुगतान स्थिति',
      'remaining_amount': 'शेष राशि',
      'change_return': 'वापसी',
      'no_change': 'कोई वापसी नहीं',
      'payment_type': 'भुगतान प्रकार',
      'card': 'कार्ड',
      'upi': 'यूपीआई',
      'wallet': 'वॉलेट',
      'cheque': 'सेके',
      'bank_transfer': 'बैंक ट्रांसफर',
      'other': 'अन्य',
      'specify': 'कुरिपிடு',

      // Menu.dart specific keys
      'billhistory': 'Bill History',
      'nobillsfound': 'No bills found',
      'settle_bill': 'Settle Bill',
      'by': 'By',
      'bill_not_found': 'Bill not found or deleted.',
      'created_by': 'Created by',
      'issued_on': 'Issued on',
      'invoice_items': 'Invoice items',
      'totalitems': 'Total items',
      'totalquantity': 'Total Qty',
      'totalamount': 'Total Amount',
      'refund': 'Refund',
      'preparing_print': 'Preparing print...',
      'printfailed': 'Print failed',
      'creditdetails': 'Credit Details',
      'creditnote': 'Credit Note',
      'no_sales_credits': 'No sales credits found',
      'no_matching_customers': 'No matching customers found',
      'total_sales_credit': 'Total Sales Credit',
      'no_purchase_credits': 'No purchase credits found',
      'no_matching_purchase_credits': 'No matching purchase credits',
      'total_purchase_credit': 'Total Purchase Credit',
      'unknown_supplier': 'Unknown Supplier',
      'purchase_credit_note': 'Purchase Credit Note',
      'credit_note_not_found': 'Credit note not found',
      'areyousure': 'Are you sure?',
      'mode': 'Mode',
      'addnewcustomer': 'Add New Customer',
      'existing_customer': 'Existing Customer',
      'name_phone_required': 'Please enter name and phone number',
      'no_customers_found': 'No customers found',
      'staffmanagement': 'Staff Management',
      'addnewstaff': 'Add New Staff',
      'savestaff': 'Save Staff',
      'staff_added_success': 'Staff added successfully',
      'sale_return': 'Sale Return',
      'thismonth': 'This Month',
      'lastmonth': 'Last Month',
      'invoicenumber': 'Invoice No.',
      'customerdetails': 'Customer Details',
      'cancel_bill': 'Cancel Bill',
      'enter_valid_amount': 'Please enter a valid amount',
      'payment_settled': 'Payment settled successfully',
      'payment_recorded': 'Payment recorded',
      'error_processing_payment': 'Error processing payment',
      'add_discount': 'Add Discount',
      'enter_note': 'Enter note...',
      'bill_updated_success': 'Bill updated successfully',
      'error_updating_bill': 'Error updating bill',

      // Reports page keys (unique additions)
      'analytics_overview': 'Analytics & Overview',
      'daybook_today': 'DayBook (Today)',
      'sales_transactions': 'Sales & Transactions',
      'item_sales_report': 'Item Sales Report',
      'inventory_products': 'Inventory & Products',
      'low_stock_products': 'Low Stock Products',
      'financials_tax': 'Financials & Tax',
      'hsn_report': 'HSN Report',
      'staff_sale_report': 'Staff Sale Report',
      'no_report_access': 'No Report Access',
      'no_report_permission_msg': 'You don\'t have permission to view any reports. Contact your administrator.',
      'hour': 'Hour',
      'currency_symbol': '₹',

      // Expenses page keys (unique additions)
      'new_expense': 'New Expense',
      'expense_details': 'Expense Details',
      'new_other_expense': 'New Other Expense',

      // Stock purchase keys (unique additions)
      'new_stock_purchase': 'New Stock Purchase',
      'purchase_details': 'Purchase Details',

      // Products page keys (unique additions)
      'filter_by_stock': 'Filter By Stock',
      'all_products': 'All Products',
      'low_stock_filter': 'Low Stock (< 10)',
      'remove': 'Remove',
      'enter_valid_quantity': 'Please enter a valid quantity',

      // Category keys (unique additions)
      'category_updated_success': 'Category updated successfully',
      'category_deleted_success': 'Category deleted successfully',
      'are_you_sure_delete': 'Are you sure you want to delete',

      // AddProduct keys (unique additions)
      'add_new_unit': 'Add New Unit',

      // Profile/Settings keys (unique additions)
      'upgrade_plan': 'Upgrade Plan',
      'restricted_access': 'Restricted Access',

      // Login keys (unique additions)
      'welcome_to': 'Welcome to',

      // Bill keys (unique additions)
      'total_payable': 'Total Payable',
      'new_customer': 'New Customer',
      'select_customer': 'Select Customer',
      'total_bill_amount': 'Total Bill Amount',
      'paid_so_far': 'Paid So Far',
      'total_bill': 'Total Bill',

      // Quotation keys (unique additions)
      'share_error': 'Share Error',
      'no_printer_selected': 'No Printer Selected',
      'select_printer_from_settings': 'Please select a printer from Settings > Printer Setup before printing.',
      'print_error': 'Print Error',

      // TaxSettings keys (unique additions)
      'create_type': 'Create Type',
      'add_tax_rate': 'Add Tax Rate',
      'update_settings': 'Update Settings',

      // StaffManagement keys (unique additions)
      'no_staff_members': 'No staff members yet',
      'invite_to_start': 'Invite someone to get started',
      'invite_new_staff': 'Invite New Staff',
      'send_invite': 'Send Invite',
      'edit_staff_member': 'Edit Staff Member',
      'remove_staff': 'Remove Staff',

      // QuotationsList keys (unique additions)
      'no_quotations_found': 'No quotations found',
      'date_newest_first': 'Date: Newest First',
      'date_oldest_first': 'Date: Oldest First',
      'amount_high_to_low': 'Amount: High to Low',
      'amount_low_to_high': 'Amount: Low to High',
      'settled': 'Settled',

      // Additional common keys (unique additions)
      'fill_required_fields': 'Please fill in required fields',
      'expense_saved_success': 'Expense saved successfully',
      'enter_category_name': 'Please enter a category name',
      'category_added_success': 'Category added successfully',
      'category_exists': 'Category already exists',

      // Saved orders keys (unique additions)
      'order_deleted': 'Order deleted',
      'delete_order': 'Delete Order',
      'no_saved_orders': 'No Saved Orders',

      // BusinessDetailsPage keys
      'complete_profile_title': 'Complete Your Profile',
      'complete_profile_subtitle': 'Please provide your business details to get started',
      'personaldetails': 'Personal Details',
      'your_name': 'Your Name',
      'enter_full_name': 'Enter your full name',
      'name_required': 'Name is required',
      'your_phone': 'Your Phone Number',
      'phone_required': 'Phone is required',
      'phone_invalid_10_digit': 'Enter valid 10-digit phone',
      'businessdetails': 'Business Details',
      'businessname': 'Business Name',
      'enter_business_name': 'Enter your business name',
      'business_name_required': 'Business name is required',
      'businessphone': 'Business Phone Number',
      'enter_business_phone': 'Enter business phone number',
      'business_phone_required': 'Business phone is required',
      'gstin_optional': 'GSTIN (Optional)',
      'enter_gstin': 'Enter GSTIN number',
      'businesslocation': 'Business Location',
      'enter_business_location': 'Enter your business location',
      'business_location_required': 'Business location is required',
      'complete_registration': 'Complete Registration',
      'business_registered_success': 'Business registered successfully!',
      'failed_to_save': 'Failed to save',

      // SubscriptionPlanPage keys
      'subscription_expiry': 'Expires',
      'permonth': '/month',
      'six_months': '6 Months',
      'peryear': '/year',
      'save_20': 'SAVE 20%',
      'perperiod': '/period',
      'full_feature_comparison': 'Full Feature Comparison',
      'freeplan': 'Free',
      'bulk_inventory': 'Bulk Inventory',
      'logo_on_bill': 'Logo on Bill',
      'customer_credit': 'Customer Credit',
      'edit_bill': 'Edit Bill',
      'taxreport': 'Tax Report',
      'import_contacts': 'Import Contacts',
      'pos_billing': 'POS Billing',
      'cloud_storage': 'Cloud Storage',
      'currentplan': 'Current Plan',
      'pay_now': 'Pay Now',
      'paymentsuccessful': 'Payment Successful! Plan Upgraded.',
      'paymentfailed': 'Payment Failed',

      // BarcodeScanner keys
      'scanbarcode': 'Scan Barcode',
      'product_added_scanned': 'Product added',
      'total_scanned': 'Total scanned',
      'products_scanned': 'Products Scanned',
      'scan_multiple_products': 'Scan multiple products\nPress back when done',

      // Language settings keys
      'available_languages': 'Available Languages',
      'language_changed_to': 'Language changed to',
      'common_translations': 'Common Translations',

      // Additional keys
      'nodata': 'No data available',
      'daybook': 'DayBook',
      'sales_summary': 'Sales Summary',
      'customername': 'Customer Name',
      'customerphone': 'Customer Phone',

      // AddProduct page localization keys
      'item_information': 'आइटम जानकारी',
      'item_name': 'आइटम का नाम',
      'leave_blank_for_price': 'बिक्री के समय मूल्य के लिए खाली छोड़ें।',
      'more_details': 'अधिक विवरण',
      'cost_price_optional': 'लागत मूल्य (वैकल्पिक)',
      'mrp_optional': 'एम.आर.पी (वैकल्पिक)',
      'product_code': 'उत्पाद कोड',
      'generate': 'जनरेट करें',
      'find': 'खोजें',
      'hsn_scn': 'एचएसएन/एससीएन',
      'barcode_info': 'बाहरी बारकोड रीडर से बारकोड जोड़ने के लिए, बारकोड फ़ील्ड पर टैप करें और बारकोड स्कैन करें',
      'unit': 'इकाई',
      'stock_unit': 'स्टॉक इकाई',
      'this_field_is_required': 'यह फ़ील्ड आवश्यक है',

      // Category.dart specific keys
      'search_categories': 'वगைகளைத் தேடு...',
      'no_categories_yet': 'இன்னும் வகைகள் இல்லை',
      'add_first_category': 'பொருட்களை ஒழுங்குபடுத்த உங்கள் முதல் வகையைச் சேர்க்கவும்',
      'no_categories_found': 'வகைகள் எதுவும் இல்லை',
      'try_searching_keywords': 'வேறு சொற்களுடன் தேட முயற்சிக்கவும்',
      'edit': 'திருத்து',
      'add_product': 'பொருள் சேர்',
      'create_new_product': 'புதிய பொருள் உருவாக்கு',
      'add_existing_product': 'ஏற்கனவே உள்ள பொருளை சேர்',
      'no_products_available': 'பொருட்கள் எதுவும் இல்லை',
      'current': 'தற்போது',
      'price_on_sale': 'விற்பனை விலை',
      'added_to': 'சேர்க்கப்பட்டது',
    },

    'ta': {
      // Common
      'app_name': 'மேக்ஸ்பில்அப்',
      'welcome': 'வரவேற்கிறோம்',
      'save': 'சேமி',
      'cancel': 'ரத்து',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'add': 'சேர்',
      'update': 'புதுப்பி',
      'search': 'தேடு',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'ok': 'சரி',
      'done': 'முடிந்தது',
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',
      'coming_soon': 'விரைவில் வரும்',
      'used': 'பயன்படுத்தப்பட்டது',
      'paid_amount': 'செலுத்திய தொகை',
      'invoice_items': 'விலைப்பட்டியல் பொருட்கள்',
      'bill_not_found': 'பில் கிடைக்கவில்லை அல்லது நீக்கப்பட்டது',
      'created_by': 'உருவாக்கியவர்',
      'issued_on': 'வழங்கப்பட்ட தேதி',
      'totalquantity': 'மொத்த அளவு',
      'invoice': 'விலைப்பட்டியல்',
      'by': 'மூலம்',

      // Navigation
      'home': 'முகப்பு',
      'sales': 'விற்பனை',
      'stocks': 'சரக்கு',
      'reports': 'அறிக்கைகள்',
      'menu': 'பட்டியல்',

      // Sales
      'new_sale': 'புதிய விற்பனை',
      'sale_all': 'அனைத்து விற்பனை',
      'quick_sale': 'விரைவு விற்பனை',
      'saved_orders': 'சேமித்த ஆர்டர்கள்',
      'complete_payment': 'கட்டணம் முடிக்கவும்',
      'add_to_cart': 'வண்டியில் சேர்',
      'cart': 'வண்டி',
      'checkout': 'செக்அவுட்',
      'payment_mode': 'கட்டண முறை',
      'cash': 'பணம்',
      'online': 'ஆன்லைன்',
      'credit': 'கடன்',
      'split_payment': 'பிரிக்கப்பட்ட கட்டணம்',

      // Bill
      'subtotal': 'துணை மொத்தம்',
      'discount': 'தள்ளுபடி',
      'tax': 'வரி',
      'total': 'மொத்தம்',
      'grand_total': 'பெரும் மொத்தம்',
      'amount_received': 'பெறப்பட்ட தொகை',
      'change': 'மாற்றம்',
      'customer': 'வாடிக்கையாளர்',
      'add_customer': 'வாடிக்கையாளர் சேர்',

      // Products/Stocks
      'products': 'பொருட்கள்',
      'category': 'வகை',
      'addproduct': 'பொருள் சேர்',
      'price': 'விலை',
      'cost_price': 'செலவு விலை',
      'mrp': 'எம்.ஆர்.பி',
      'quantity': 'அளவு',
      'barcode': 'பார்கோடு',
      'stock': 'சரக்கு',
      'in_stock': 'சரக்கில் உள்ளது',
      'out_of_stock': 'சரக்கு தீர்ந்தது',
      'low_stock': 'குறைவான சரக்கு',

      // Tax
      'tax_settings': 'வரி அமைப்புகள்',
      'add_tax': 'வரி சேர்',
      'tax_name': 'வரி பெயர்',
      'tax_percentage': 'வரி %',
      'price_includes_tax': 'விலையில் வரி உள்ளது',
      'price_without_tax': 'வரி இல்லாத விலை',
      'zero_rated_tax': 'பூஜ்ஜிய வரி',
      'exempt_tax': 'வரி விலக்கு',

      // Settings
      'profile': 'சுயவிவரம்',
      'business_details': 'வணிக விவரங்கள்',
      'business_name': 'வணிக பெயர்',
      'business_phone': 'வணிக தொலைபேசி',
      'business_location': 'வணிக இடம்',
      'business_email': 'வணிக மின்னஞ்சல்',
      'gstin': 'ஜிஎஸ்டிஐஎன்',
      'choose_language': 'மொழியைத் தேர்ந்தெடு',
      'theme': 'தீம்',
      'printer_setup': 'அச்சுப்பொறி அமைப்பு',
      'receipt_customization': 'ரசீது தனிப்பயனாக்கம்',
      'feature_settings': 'அம்ச அமைப்புகள்',
      'help': 'உதவி',
      'about': 'பற்றி',

      // Reports
      'daily_report': 'தினசரி அறிக்கை',
      'monthly_report': 'மாதாந்திர அறிக்கை',
      'sales_report': 'விற்பனை அறிக்கை',
      'stock_report': 'சரக்கு அறிக்கை',
      'tax_report': 'வரி அறிக்கை',
      'profit_loss': 'இலாபம் & நஷ்டம்',

      // Messages
      'product_added': 'பொருள் வெற்றிகரமாக சேர்க்கப்பட்டது',
      'product_updated': 'பொருள் புதுப்பிக்கப்பட்டது',
      'product_deleted': 'பொருள் நீக்கப்பட்டது',
      'sale_completed': 'விற்பனை முடிந்தது',
      'payment_successful': 'கட்டணம் வெற்றி',
      'payment_failed': 'கட்டணம் தோல்வி',
      'no_items_in_cart': 'வண்டியில் பொருட்கள் இல்லை',
      'invalid_input': 'தவறான உள்ளீடு',
      'required_field': 'இந்த புலம் தேவை',
      'confirm_delete': 'நிச்சயமாக நீக்க விரும்புகிறீர்களா?',
      'saved_offline': 'ஆஃப்லைனில் சேமிக்கப்பட்டது. ஆன்லைனில் ஒத்திசைக்கப்படும்.',
      'sync_completed': 'ஒத்திசைவு முடிந்தது',

      // Additional Pages
      'quotations': 'மேற்கோள்கள்',
      'create_quotation': 'மேற்கோள் உருவாக்கு',
      'quotation_list': 'மேற்கோள் பட்டியல்',
      'convert_to_sale': 'விற்பனையாக மாற்று',
      'expenses': 'செலவுகள்',
      'other_expenses': 'பிற செலவுகள்',
      'add_expense': 'செலவு சேர்',
      'expense_category': 'செலவு வகை',
      'categories': 'வகைகள்',
      'add_category': 'வகை சேர்',
      'staff_management': 'பணியாளர் மேலாண்மை',
      'add_staff': 'பணியாளர் சேர்',
      'customers': 'வாடிக்கையாளர்கள்',
      'supplier': 'விநியோகஸ்தர்',
      'purchase': 'கொள்முதல்',
      'stock_purchase': 'சரக்கு கொள்முதல்',
      'view': 'காண்க',
      'print': 'அச்சிடு',
      'share': 'பகிர்',
      'receipt': 'ரசீது',
      'date': 'தேதி',
      'time': 'நேரம்',
      'from': 'இருந்து',
      'to': 'வரை',
      'all': 'அனைத்தும்',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'this_week': 'இந்த வாரம்',
      'this_month': 'இந்த மாதம்',
      'custom': 'தனிப்பயன்',
      'apply': 'பயன்படுத்து',
      'reset': 'மீட்டமை',
      'export': 'ஏற்றுமதி',
      'download': 'பதிவிறக்கு',
      'upload': 'பதிவேற்று',
      'back': 'பின்',
      'next': 'அடுத்து',
      'previous': 'முந்தைய',
      'finish': 'முடி',
      'skip': 'தவிர்',
      'continue': 'தொடர்',
      'close': 'மூடு',
      'open': 'திற',
      'refresh': 'புதுப்பி',
      'sync': 'ஒத்திசை',
      'online_mode': 'ஆன்லைன் பயன்முறை',
      'offline_mode': 'ஆஃப்லைன் பயன்முறை',
      'select': 'தேர்ந்தெடு',
      'select_all': 'அனைத்தையும் தேர்ந்தெடு',
      'deselect_all': 'அனைத்தையும் தேர்வு நீக்கு',
      'filter': 'வடிகட்டு',
      'sort': 'வரிசைப்படுத்து',
      'ascending': 'ஏறுவரிசை',
      'descending': 'இறங்குவரிசை',
      'name': 'பெயர்',
      'description': 'விளக்கம்',
      'amount': 'தொகை',
      'paid': 'செலுத்தப்பட்டது',
      'unpaid': 'செலுத்தப்படாதது',
      'pending': 'நிலுவையில்',
      'completed': 'முடிந்தது',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'active': 'செயல்படும்',
      'inactive': 'செயலற்றது',
      'enabled': 'இயக்கப்பட்டது',
      'disabled': 'முடக்கப்பட்டது',
      'phone': 'தொலைபேசி',
      'email': 'மின்னஞ்சல்',
      'address': 'முகவரி',
      'city': 'நகரம்',
      'state': 'மாநிலம்',
      'country': 'நாடு',
      'pincode': 'பின்கோட்',
      'notes': 'குறிப்புகள்',
      'remarks': 'கருத்துகள்',
      'status': 'நிலை',
      'action': 'செயல்',
      'actions': 'செயல்கள்',
      'details': 'விவரங்கள்',
      'summary': 'சுருக்கம்',
      'billing': 'பில்லிங்',
      'shipping': 'ஷிப்பிங்',
      'payment': 'கட்டணம்',
      'order': 'ஆர்டர்',
      'orders': 'ஆர்டர்கள்',
      'item': 'பொருள்',
      'items': 'பொருட்கள்',
      'unit': 'அலகு',
      'rate': 'விலை',
      'gst': 'ஜிஎஸ்டி',
      'vat': 'வேட்',
      'cgst': 'சிஜிஎஸ்டி',
      'sgst': 'எஸ்ஜிஎஸ்டி',
      'igst': 'ஐஜிஎஸ்டி',
      'total_items': 'மொத்த பொருட்கள்',
      'total_amount': 'மொத்த தொகை',
      'due_amount': 'நிலுவை தொகை',
      'balance': 'இருப்பு',
      'credit_limit': 'கடன் வரம்பு',
      'available': 'கிடைக்கிறது',
      'unavailable': 'கிடைக்கவில்லை',

      // Additional UI strings - using English as placeholders for other languages
      'bill_history': 'பில் வரலாறு',
      'bill_summary': 'பில் சுருக்கம்',
      'bill_to': 'பில் செலுத்துபவர்',
      'bill_cancelled': 'பில் ரத்து',
      'bill_description': 'பில் விவரம்',
      'clear': 'அழி',
      'clear_order': 'ஆர்டர் அழி',
      'clear_all': 'அனைத்தையும் அழி',
      'report': 'அறிக்கை',
      'no_products_found': 'பொருட்கள் எதுவும் இல்லை',
      'product_not_found': 'பொருள் கிடைக்கவில்லை',
      'max_stock_reached': 'அதிகபட்ச சரக்கு எட்டப்பட்டது! ({0} உள்ளது)',
      'enter_quantity': 'அளவை உள்ளிடவும்',
      'saved': 'சேமிக்கப்பட்டது',
      'quotation': 'மேற்கோள்',
      'credit_notes': 'கிரெடிட் நோட்டுகள்',
      'add_credit_note': 'கிரெடிட் நோட் சேர்க்கவும்',
      'credit_details': 'கிரெடிட் விவரங்கள்',
      'available_credit_notes': 'கிடைக்கும் கிரெடிட் நோட்டுகள்',
      'bill_wise': 'பில் அடிப்படையில்',
      'customer_details': 'வாடிக்கையாளர் விவரங்கள்',
      'add_customer_details': 'வாடிக்கையாளர் விவரங்களைச் சேர்க்கவும்',
      'add_new_customer': 'புதிய வாடிக்கையாளரைச் சேர்க்கவும்',
      'customer_name': 'வாடிக்கையாளர் பெயர்',
      'customer_phone': 'வாடிக்கையாளர் தொலைபேசி',
      'payment_method': 'கட்டண முறை',
      'cash_payment': 'நகதாக கட்டணம்',
      'online_payment': 'ஆன்லைன் கட்டணம்',
      'credit_payment': 'கடன் கட்டணம்',
      'split': 'பிரிக்கவும்',
      'received': 'பெறப்பட்டது',
      'due': 'கடன்',
      'advance': 'முன்பணம்',
      'internal_note': 'உள்ளகுறிப்பு',
      'add_internal_note': 'உள்ளகுறிப்பு சேர்க்கவும்',
      'add_note': 'குறிப்பு சேர்க்கவும்',
      'discount_percent': 'தள்ளுபடி (%)',
      'discount_amount': 'தள்ளுபடி தொகை',
      'price_with_tax': 'வரி உடன் விலை',
      'tax_amount': 'வரி தொகை',
      'payment_details': 'கட்டண விவரங்கள்',
      'billing_details': 'பில்லிங் விவரங்கள்',
      'proceed': 'முன்னேறு',
      'discard': 'தவிர்',
      'confirm': 'உறுதிப்படுத்தவும்',
      'warning': 'எச்சரிக்கை',
      'are_you_sure': 'நீங்கள் உறுதியாக உள்ளீர்களா?',
      'cannot_be_undone': 'இந்த செயல் முன்னணி செய்ய முடியாது',
      'discard_bill': 'பில் தவிர்க்கவும்',
      'are_you_sure_discard': 'இந்த பிலைக் கைவிட விரும்புகிறீர்களா?',
      'delete_product': 'பொருளை நீக்கு',
      'are_you_sure_delete_product': 'இந்த பொருளை நீக்க விரும்புகிறீர்களா?',
      'item_name': 'பொருள் பெயர்',
      'hsn_code': 'HSN குறியீடு',
      'unit_price': 'அலகு விலை',
      'selling_price': 'விற்பனை விலை',
      'stock_enabled': 'சரக்கு செயல்படுத்தப்பட்டது',
      'current_stock': 'தற்போதைய சரக்கு',
      'low_stock_alert': 'குறைந்த சரக்கு எச்சரிக்கை',
      'min_stock': 'குறைந்தபட்ச சரக்கு',
      'max_stock': 'அதிகபட்ச சரக்கு',
      'reorder_level': 'மீண்டும் ஆர்டர் நிலை',
      'category_name': 'வகை பெயர்',
      'add_category_name': 'வகை பெயரைச் சேர்க்கவும்',
      'delete_category': 'வகையை நீக்கு',
      'are_you_sure_delete_category': 'இந்த வகையை நீக்க விரும்புகிறீர்களா?',
      'edit_product': 'பொருளை திருத்து',
      'edit_category': 'வகையை திருத்து',
      'save_product': 'பொருளைச் சேமிக்கவும்',
      'save_category': 'வகையைச் சேமிக்கவும்',
      'required': 'தேவை',
      'invalid': 'தவறானது',
      'enter_valid_value': 'சரியான மதிப்பை உள்ளிடவும்',
      'expense_name': 'செலவின் பெயர்',
      'expense_amount': 'செலவின் தொகை',
      'expense_date': 'செலவின் தேதி',
      'expense_type': 'செலவின் வகை',
      'add_expense_category': 'செலவுப் பிரிவைச் சேர்க்கவும்',
      'expense_categories': 'செலவுப் பிரிவுகள்',
      'staff_name': 'பணியாளரின் பெயர்',
      'staff_phone': 'பணியாளரின் தொலைபேசி',
      'staff_email': 'பணியாளரின் மின்னஞ்சல்',
      'staff_role': 'பணியாளரின் பங்கு',
      'permissions': 'அனுமதிகள்',
      'grant_permissions': 'அனுமதிகளை வழங்கவும்',
      'role': 'பங்கு',
      'admin': 'நிர்வாகி',
      'staff': 'பணியாளர்',
      'cashier': 'காசியர்',
      'manager': 'மேலாளர்',
      'add_new_staff': 'புதிய பணியாளரைச் சேர்க்கவும்',
      'edit_staff': 'பணியாளரைத் திருத்து',
      'delete_staff': 'பணியாளரை நீக்கு',
      'are_you_sure_delete_staff': 'இந்த பணியாளரை நீக்க விரும்புகிறீர்களா?',
      'login': 'உள்நுழைவு',
      'email_phone': 'மின்னஞ்சல் / தொலைபேசி',
      'password': 'கடவுச்சொல்',
      'forgot_password': 'கடவுச்சொல் மறந்துவிட்டீர்களா',
      'sign_in': 'உள்நுழையவும்',
      'sign_up': 'பதிவு செய்யவும்',
      'sign_in_with_google': 'கூகிள் மூலம் உள்நுழைக',
      'create_account': 'கணக்கை உருவாக்கவும்',
      'already_have_account': 'முன்னதாகவே கணக்கு உள்ளதா?',
      'dont_have_account': 'கணக்கு இல்லைதா?',
      'enter_email': 'மின்னஞ்சலை உள்ளிடவும்',
      'enter_phone': 'தொலைபேசியை உள்ளிடவும்',
      'enter_password': 'கடவுச்சொல்லை உள்ளிடவும்',
      'invalid_email': 'தவறான மின்னஞ்சல்',
      'invalid_phone': 'தவறான தொலைபேசி',
      'password_too_short': 'கடவுச்சொல் மிகவும் குறுகியது',
      'login_failed': 'உள்நுழைவு தோல்வியுற்றது',
      'signup_failed': 'பதிவு தோல்வியுற்றது',
      'logout_confirm': 'நீங்கள் உண்மையில் வெளியேற விரும்புகிறீர்களா?',
      'subscription_plan': 'சப்ஸ்கிரிப்ஷன் திட்டம்',
      'choose_plan': 'திட்டத்தைத் தேர்ந்தெடு',
      'current_plan': 'தற்போதைய திட்டம்',
      'free_plan': 'இலவச திட்டம்',
      'basic_plan': 'அடிப்படை திட்டம்',
      'premium_plan': 'பிரீமியம் திட்டம்',
      'enterprise_plan': 'என்டர்பிரைஸ் திட்டம்',
      'upgrade': 'மேம்படுத்து',
      'upgrade_now': 'இப்போது மேம்படுத்தவும்',
      'upgrade_to_premium': 'பிரீமியமாக மேம்படுத்தவும்',
      'features': 'அம்சங்கள்',
      'per_month': 'மாதத்திற்கு',
      'per_year': 'வருடத்திற்கு',
      'best_value': 'சிறந்த மதிப்பு',
      'most_popular': 'மிகவும் பிரபலமானது',
      'contact_us': 'எங்களை தொடர்பு கொள்ளவும்',
      'terms_conditions': 'நிபந்தனைகள் & விதிமுறைகள்',
      'privacy_policy': 'தனியுரிமை கொள்கை',
      'version': 'பதிப்பு',
      'build': 'கட்டமைப்பு',
      'developed_by': 'உருவாக்கப்பட்டது',
      'powered_by': 'சக்தி வழங்கப்பட்டது',
      'all_rights_reserved': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டுள்ளன',
      'language': 'மொழி',
      'currency': 'நாணயம்',
      'timezone': 'காலவெளி',
      'notifications': 'அறிக்கைகள்',
      'enable_notifications': 'அறிக்கைகளை இயக்கவும்',
      'sound': 'சொல்',
      'vibration': 'அதிர்வு',
      'backup': 'மூலபதிவு',
      'restore': 'மீட்டமை',
      'backup_restore': 'மூலபதிவு & மீட்டமை',
      'create_backup': 'மூலபதிவு உருவாக்கவும்',
      'restore_backup': 'மூலபதிவை மீட்டமைக்கவும்',
      'last_backup': 'கடைசி மூலபதிவு',
      'no_backup': 'மூலபதிவு இல்லை',
      'backup_success': 'மூலபதிவு வெற்றிகரமாக செய்யப்பட்டது',
      'restore_success': 'மீட்டமைப்பு வெற்றிகரமாக செய்யப்பட்டது',
      'backup_failed': 'மூலபதிவு தோல்வியுற்றது',
      'restore_failed': 'மீட்டமைப்பு தோல்வியுற்றது',
      'analytics': 'பகுப்பாய்வு',
      'dashboard': 'கண்காணிப்பு பலகை',
      'overview': 'மேலோட்டம்',
      'statistics': 'புள்ளிவிவரங்கள்',
      'charts': 'கோஷ்டிகள்',
      'graphs': 'கிராஃப்கள்',
      'top_products': 'சிறந்த தயாரிப்புகள்',
      'top_customers': 'சிறந்த வாடிக்கையாளர்கள்',
      'top_categories': 'சிறந்த வகைகள்',
      'recent_sales': 'சமீபத்திய விற்பனைகள்',
      'recent_orders': 'சமீபத்திய ஆர்டர்கள்',
      'pending_orders': 'நிலுவையில் உள்ள ஆர்டர்கள்',
      'completed_orders': 'முடிக்கப்பட்ட ஆர்டர்கள்',
      'cancelled_orders': 'ரத்து செய்யப்பட்ட ஆர்டர்கள்',
      'total_sales': 'மொத்த விற்பனை',
      'total_revenue': 'மொத்த வருவாய்',
      'total_profit': 'மொத்த லாபம்',
      'total_orders': 'மொத்த ஆர்டர்கள்',
      'total_customers': 'மொத்த வாடிக்கையாளர்கள்',
      'total_products': 'மொத்த தயாரிப்புகள்',
      'income': 'வருமானம்',
      'expense': 'செலவு',
      'profit': 'லாபம்',
      'loss': 'நஷ்டம்',
      'revenue': 'வருவாய்',
      'growth': 'வளர்ச்சி',
      'decline': 'குறைவு',
      'percentage': 'சதவீதம்',
      'change_from_last_month': 'கடந்த மாதத்திலிருந்து மாற்றம்',
      'change_from_last_week': 'கடந்த வாரத்திலிருந்து மாற்றம்',
      'last_7_days': 'கடந்த 7 நாட்கள்',
      'last_30_days': 'கடந்த 30 நாட்கள்',
      'last_90_days': 'கடந்த 90 நாட்கள்',
      'this_year': 'இந்த ஆண்டு',
      'last_year': 'கடந்த ஆண்டு',
      'custom_range': 'தனிப்பயன் வரம்பு',
      'start_date': 'தொடக்க தேதி',
      'end_date': 'முடிவு தேதி',
      'generate_report': 'அறிக்கையை உருவாக்கவும்',
      'download_report': 'அறிக்கையை பதிவிறக்கவும்',
      'print_report': 'அறிக்கையை அச்சிடவும்',
      'share_report': 'அறிக்கையை பகிரவும்',
      'email_report': 'அறிக்கையை மின்னஞ்சல் செய்யவும்',
      'pdf_report': 'PDF அறிக்கை',
      'excel_report': 'Excel அறிக்கை',
      'report_generated': 'அறிக்கை வெற்றிகரமாக உருவாக்கப்பட்டது',
      'report_failed': 'அறிக்கை உருவாக்குவதில் தோல்வி',
      'no_data': 'தரவு இல்லை',
      'no_results': 'எந்த முடிவுகளும் கிடைக்கவில்லை',
      'try_again': 'மீண்டும் முயற்சிக்கவும்',
      'retry': 'மீண்டும் முயற்சிக்கவும்',
      'reload': 'மீண்டும் ஏற்றவும்',
      'something_went_wrong': 'ஏதோ தவறு நடந்தது',
      'network_error': 'நெட்வொர்க் பிழை',
      'server_error': 'சர்வர் பிழை',
      'connection_failed': 'கணினி இணைப்பு தோல்வியுற்றது',
      'please_check_internet': 'உங்கள் இன்டர்நெட் இணைப்பை சரிபார்க்கவும்',
      'offline': 'ஆஃப்லைன்',
      'connecting': 'இணைக்கிறது...',
      'syncing': 'ஒத்திசைக்கிறது...',
      'sync_failed': 'ஒத்திசைவு தோல்வியுற்றது',
      'sync_success': 'வெற்றிகரமாக ஒத்திசைக்கப்பட்டது',
      'last_synced': 'கடைசி ஒத்திசைவு',
      'never_synced': 'எப்போது ஒத்திசைக்கப்படவில்லை',
      'sync_now': 'இப்போது ஒத்திசை',
      'auto_sync': 'ஆட்டோ ஒத்திசைவு',
      'manual_sync': 'கைமுறையீட்டு ஒத்திசைவு',
      'sync_settings': 'ஒத்திசைவு அமைப்புகள்',
      'data_usage': 'தரவுகோல் பயன்பாடு',
      'storage': 'சேமிப்பு',
      'clear_cache': 'கேஷ் அழி',
      'clear_data': 'தரவை அழி',
      'cache_cleared': 'கேஷ் அழிக்கப்பட்டது',
      'data_cleared': 'தரவு அழிக்கப்பட்டது',
      'confirm_clear': 'நீக்க விரும்புகிறீர்களா?',
      'scanning': 'ஸ்கேன் செய்யப்படுகிறது...',
      'scan_barcode': 'பார்கோடு ஸ்கேன்',
      'scan_qr': 'QR கோடு ஸ்கேன்',
      'camera_permission': 'கேமரா அனுமதி',
      'camera_permission_required': 'கேமரா அனுமதி தேவை',
      'grant_permission': 'அனுமதி வழங்கு',
      'permission_denied': 'அனுமதி மறுக்கப்பட்டது',
      'enable_from_settings': 'அமைப்புகளில் இருந்து இயக்கவும்',
      'printer_not_found': 'அச்சுப்பொறி கிடைக்கவில்லை',
      'printer_connected': 'அச்சுப்பொறி இணைக்கப்பட்டது',
      'printer_disconnected': 'அச்சுப்பொறி இணைப்பு துண்டிக்கப்பட்டது',
      'connecting_printer': 'அச்சுப்பொறிக்கு இணைக்கிறது...',
      'print_settings': 'அச்சுப்பொறி அமைப்புகள்',
      'paper_size': 'காகித அளவு',
      'print_quality': 'அச்சு தரம்',
      'copies': 'பதிப்புகள்',
      'print_preview': 'அச்சு முன்னோட்டம்',
      'printing': 'அச்சிடுகிறது...',
      'print_success': 'வெற்றிகரமாக அச்சிடப்பட்டது',
      'print_failed': 'அச்சிடுவதில் தோல்வி',
      'bluetooth': 'ப்ளூடூத்',
      'wifi': 'வைஃபை',
      'usb': 'யூஎஸ்பி',
      'network': 'நெட்வொர்க்',
      'select_printer': 'அச்சுப்பொறியைத் தேர்ந்தெடு',
      'add_printer': 'அச்சுப்பொறியைச் சேர்க்கவும்',
      'remove_printer': 'அச்சுப்பொறியை நீக்கு',
      'test_print': 'சோதனை அச்சு',
      'invoice_number': 'விலைப்பட்டியல் எண்',
      'bill_number': 'பில் எண்',
      'order_number': 'ஆர்டர் எண்',
      'reference_number': 'குறிப்பு எண்',
      'transaction_id': 'பரிமாற்ற ஐடி',
      'payment_id': 'கட்டணம் ஐடி',
      'receipt_number': 'ரசீது எண்',
      'customer_copy': 'வாடிக்கையாளர் நகல்',
      'merchant_copy': 'வணிகர் நகல்',
      'thank_you': 'நன்றி',
      'visit_again': 'மீண்டும் வருக',
      'terms': 'விதிமுறைகள்',
      'signature': 'கையொப்பம்',
      'authorized_signature': 'அதிகாரப்பூர்வ கையொப்பம்',
      'stamp': 'முத்திரை',
      'company_stamp': 'கம்பனியின் முத்திரை',
      'powered_by_maxbillup': 'MaxBillUp மூலம் இயக்கப்படுகிறது',
      'generated_by': 'உருவாக்கப்பட்டது',
      'page': 'பக்கம்',
      'of': 'இன்',
      'sub_total': 'உப மொத்தம்',
      'taxable_amount': 'வரி விதிக்கக்கூடிய தொகை',
      'tax_details': 'வரி விவரங்கள்',
      'round_off': 'சுற்றி விடு',
      'net_amount': 'நிகர தொகை',
      'amount_in_words': 'வார்த்தைகளில் தொகை',
      'rupees': 'ரூபாய்',
      'only': 'மட்டும்',
      'payment_status': 'கட்டண நிலை',
      'remaining_amount': 'மீதமுள்ள தொகை',
      'change_return': 'மாற்றம் திரும்பவும்',
      'no_change': 'மாற்றம் இல்லை',
      'payment_type': 'கட்டண வகை',
      'card': 'கார்டு',
      'upi': 'யூபிஐ',
      'wallet': 'வாலெட்',
      'cheque': 'சேக்கு',
      'bank_transfer': 'பங்க் பரிமாற்றம்',
      'other': 'மற்றவை',
      'specify': 'குறிப்பிடவும்',

      // New additions from English
      'analytics_overview': 'பகுப்பாய்வு மற்றும் மேலோட்டம்',
      'daybook_today': 'தினசரி புத்தகம் (இன்று)',
      'sales_transactions': 'விற்பனை மற்றும் பரிவர்த்தனைகள்',
      'item_sales_report': 'பொருள் விற்பனை அறிக்கை',
      'inventory_products': 'சரக்கு மற்றும் பொருட்கள்',
      'low_stock_products': 'குறைந்த சரக்கு பொருட்கள்',
      'financials_tax': 'நிதி மற்றும் வரி',
      'hsn_report': 'HSN அறிக்கை',
      'staff_sale_report': 'ஊழியர் விற்பனை அறிக்கை',
      'no_report_access': 'அறிக்கை அணுகல் இல்லை',
      'no_report_permission_msg': 'எந்த அறிக்கையையும் பார்க்க உங்களுக்கு அனுமதி இல்லை. உங்கள் நிர்வாகியை தொடர்பு கொள்ளவும்.',
      'hour': 'மணி',
      'new_expense': 'புதிய செலவு',
      'expense_details': 'செலவு விவரங்கள்',
      'new_other_expense': 'புதிய மற்ற செலவு',
      'new_stock_purchase': 'புதிய சரக்கு கொள்முதல்',
      'purchase_details': 'கொள்முதல் விவரங்கள்',
      'filter_by_stock': 'சரக்கு மூலம் வடிகட்டு',
      'all_products': 'அனைத்து பொருட்கள்',
      'low_stock_filter': 'குறைந்த சரக்கு (< 10)',
      'remove': 'அகற்று',
      'enter_valid_quantity': 'சரியான அளவை உள்ளிடவும்',
      'category_updated_success': 'வகை வெற்றிகரமாக புதுப்பிக்கப்பட்டது',
      'category_deleted_success': 'வகை வெற்றிகரமாக நீக்கப்பட்டது',
      'are_you_sure_delete': 'நிச்சயமாக நீக்க விரும்புகிறீர்களா',
      'add_new_unit': 'புதிய அலகு சேர்',
      'upgrade_plan': 'திட்டத்தை மேம்படுத்து',
      'restricted_access': 'தடைசெய்யப்பட்ட அணுகல்',
      'welcome_to': 'வரவேற்கிறோம்',
      'total_payable': 'மொத்த செலுத்த வேண்டியது',
      'new_customer': 'புதிய வாடிக்கையாளர்',
      'select_customer': 'வாடிக்கையாளரைத் தேர்ந்தெடு',
      'total_bill_amount': 'மொத்த பில் தொகை',
      'paid_so_far': 'இதுவரை செலுத்தப்பட்டது',
      'total_bill': 'மொத்த பில்',
      'share_error': 'பகிர்வு பிழை',
      'no_printer_selected': 'அச்சுப்பொறி தேர்ந்தெடுக்கப்படவில்லை',
      'select_printer_from_settings': 'அச்சிடுவதற்கு முன் அமைப்புகள் > அச்சுப்பொறி அமைப்பில் இருந்து ஒரு அச்சுப்பொறியை தேர்ந்தெடுக்கவும்.',
      'print_error': 'அச்சு பிழை',
      'create_type': 'வகையை உருவாக்கு',
      'add_tax_rate': 'வரி விகிதம் சேர்',
      'update_settings': 'அமைப்புகளை புதுப்பி',
      'no_staff_members': 'இதுவரை ஊழியர் உறுப்பினர்கள் இல்லை',
      'invite_to_start': 'தொடங்க ஒருவரை அழைக்கவும்',
      'invite_new_staff': 'புதிய ஊழியரை அழை',
      'send_invite': 'அழைப்பு அனுப்பு',
      'edit_staff_member': 'ஊழியர் உறுப்பினரை திருத்து',
      'remove_staff': 'ஊழியரை அகற்று',
      'no_quotations_found': 'ஒதுக்கீடுகள் எதுவும் கிடைக்கவில்லை',
      'date_newest_first': 'தேதி: புதியது முதலில்',
      'date_oldest_first': 'தேதி: பழையது முதலில்',
      'amount_high_to_low': 'தொகை: உயர்ந்ததிலிருந்து குறைந்தது',
      'amount_low_to_high': 'தொகை: குறைந்ததிலிருந்து உயர்ந்தது',
      'settled': 'தீர்க்கப்பட்டது',
      'fill_required_fields': 'தேவையான புலங்களை நிரப்பவும்',
      'expense_saved_success': 'செலவு வெற்றிகரமாக சேமிக்கப்பட்டது',
      'enter_category_name': 'வகை பெயரை உள்ளிடவும்',
      'category_added_success': 'வகை வெற்றிகரமாக சேர்க்கப்பட்டது',
      'category_exists': 'வகை ஏற்கனவே உள்ளது',
      'order_deleted': 'ஆர்டர் நீக்கப்பட்டது',
      'delete_order': 'ஆர்டரை நீக்கு',
      'no_saved_orders': 'சேமிக்கப்பட்ட ஆர்டர்கள் இல்லை',

      // BusinessDetailsPage keys
      'complete_profile_title': 'உங்கள் சுயவிவரத்தை முடிக்கவும்',
      'complete_profile_subtitle': 'தொடங்க உங்கள் வணிக விவரங்களை வழங்கவும்',
      'personaldetails': 'தனிப்பட்ட விவரங்கள்',
      'your_name': 'உங்கள் பெயர்',
      'enter_full_name': 'உங்கள் முழு பெயரை உள்ளிடவும்',
      'name_required': 'பெயர் தேவை',
      'your_phone': 'உங்கள் தொலைபேசி எண்',
      'phone_required': 'தொலைபேசி தேவை',
      'phone_invalid_10_digit': 'சரியான 10-இலக்க தொலைபேசி உள்ளிடவும்',
      'businessdetails': 'வணிக விவரங்கள்',
      'businessname': 'வணிக பெயர்',
      'enter_business_name': 'உங்கள் வணிக பெயரை உள்ளிடவும்',
      'business_name_required': 'வணிக பெயர் தேவை',
      'businessphone': 'வணிக தொலைபேசி எண்',
      'enter_business_phone': 'வணிக தொலைபேசி எண்ணை உள்ளிடவும்',
      'business_phone_required': 'வணிக தொலைபேசி தேவை',
      'gstin_optional': 'GSTIN (விருப்பத்தேர்வு)',
      'enter_gstin': 'GSTIN எண்ணை உள்ளிடவும்',
      'businesslocation': 'வணிக இடம்',
      'enter_business_location': 'உங்கள் வணிக இடத்தை உள்ளிடவும்',
      'business_location_required': 'வணிக இடம் தேவை',
      'complete_registration': 'பதிவை முடிக்கவும்',
      'business_registered_success': 'வணிகம் வெற்றிகரமாக பதிவு செய்யப்பட்டது!',
      'failed_to_save': 'சேமிக்க முடியவில்லை',

      // SubscriptionPlanPage keys
      'subscription_expiry': 'காலாவதி',
      'permonth': '/மாதம்',
      'six_months': '6 மாதங்கள்',
      'peryear': '/வருடம்',
      'save_20': '20% சேமிக்கவும்',
      'perperiod': '/காலம்',
      'full_feature_comparison': 'முழு அம்ச ஒப்பீடு',
      'freeplan': 'இலவசம்',
      'bulk_inventory': 'மொத்த சரக்கு',
      'logo_on_bill': 'பில்லில் லோகோ',
      'customer_credit': 'வாடிக்கையாளர் கடன்',
      'edit_bill': 'பில் திருத்து',
      'taxreport': 'வரி அறிக்கை',
      'import_contacts': 'தொடர்புகளை இறக்கு',
      'pos_billing': 'POS பில்லிங்',
      'cloud_storage': 'கிளவுட் சேமிப்பு',
      'currentplan': 'தற்போதைய திட்டம்',
      'pay_now': 'இப்போது செலுத்து',
      'paymentsuccessful': 'பணம் செலுத்தப்பட்டது! திட்டம் மேம்படுத்தப்பட்டது.',
      'paymentfailed': 'பணம் செலுத்த முடியவில்லை',

      // BarcodeScanner keys
      'scanbarcode': 'பார்கோடு ஸ்கேன்',
      'product_added_scanned': 'பொருள் சேர்க்கப்பட்டது',
      'total_scanned': 'மொத்தம் ஸ்கேன் செய்யப்பட்டது',
      'products_scanned': 'ஸ்கேன் செய்யப்பட்ட பொருட்கள்',
      'scan_multiple_products': 'பல பொருட்களை ஸ்கேன் செய்யவும்\nமுடிந்ததும் பின் அழுத்தவும்',

      // Language settings keys
      'available_languages': 'கிடைக்கும் மொழிகள்',
      'language_changed_to': 'மொழி மாற்றப்பட்டது',
      'common_translations': 'பொதுவான மொழிபெயர்ப்புகள்',

      // Additional keys
      'nodata': 'தரவு இல்லை',
      'daybook': 'தினசரி புத்தகம்',
      'sales_summary': 'விற்பனை சுருக்கம்',
      'customername': 'வாடிக்கையாளர் பெயர்',
      'customerphone': 'வாடிக்கையாளர் தொலைபேசி',

      // AddProduct page localization keys
      'item_information': 'आइटम जानकारी',
      'item_name': 'आइटम का नाम',
      'leave_blank_for_price': 'बिक्री के समय मूल्य के लिए खाली छोड़ें।',
      'more_details': 'अधिक विवरण',
      'cost_price_optional': 'लागत मूल्य (वैकल्पिक)',
      'mrp_optional': 'एम.आर.पी (वैकल्पिक)',
      'product_code': 'उत्पाद कोड',
      'generate': 'जनरेट करें',
      'find': 'खोजें',
      'hsn_scn': 'एचएसएन/एससीएन',
      'barcode_info': 'बाहरी बारकोड रीडर से बारकोड जोड़ने के लिए, बारकोड फ़ील्ड पर टैप करें और बारकोड स्कैन करें',
      'unit': 'इकाई',
      'stock_unit': 'स्टॉक इकाई',
      'this_field_is_required': 'यह फ़ील्ड आवश्यक है',

      // Category.dart specific keys
      'search_categories': 'வகைகளைத் தேடு...',
      'no_categories_yet': 'இன்னும் வகைகள் இல்லை',
      'add_first_category': 'பொருட்களை ஒழுங்குபடுத்த உங்கள் முதல் வகையைச் சேர்க்கவும்',
      'no_categories_found': 'வகைகள் எதுவும் இல்லை',
      'try_searching_keywords': 'வேறு சொற்களுடன் தேட முயற்சிக்கவும்',
      'edit': 'திருத்து',
      'add_product': 'பொருள் சேர்',
      'create_new_product': 'புதிய பொருள் உருவாக்கு',
      'add_existing_product': 'ஏற்கனவே உள்ள பொருளை சேர்',
      'no_products_available': 'பொருட்கள் எதுவும் இல்லை',
      'current': 'தற்போது',
      'price_on_sale': 'விற்பனை விலை',
      'added_to': 'சேர்க்கப்பட்டது',
    },

    'fr': {}, // Will fallback to English
    'es': {}, // Will fallback to English
    'ms': {}, // Will fallback to English
    'bn': {}, // Will fallback to English
    'uz': {}, // Will fallback to English
    'ru': {}, // Will fallback to English
  };
}

