import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguageCode = 'en'; // Default to English

  String get currentLanguageCode => _currentLanguageCode;

  // Language configurations
  final Map<String, Map<String, String>> _languages = {
    'en': {'name': 'English', 'native': 'English'},
    'fr': {'name': 'Français', 'native': 'French'},
    'hi': {'name': 'हिंदी', 'native': 'Hindi'},
    'es': {'name': 'Español', 'native': 'Spanish'},
    'ta': {'name': 'தமிழ்', 'native': 'Tamil'},
    'ms': {'name': 'Bahasa Melayu', 'native': 'Malay'},
    'bn': {'name': 'বাংলা', 'native': 'Bangla'},
    'uz': {'name': 'O\'zbek', 'native': 'Uzbek'},
    'ru': {'name': 'Русский', 'native': 'Russian'},
  };

  Map<String, Map<String, String>> get languages => _languages;

  String get currentLanguageName => _languages[_currentLanguageCode]?['name'] ?? 'English';

  // Load saved language preference
  Future<void> loadLanguagePreference() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final savedLanguage = prefs.getString('app_language');
      if (savedLanguage != null && _languages.containsKey(savedLanguage)) {
        _currentLanguageCode = savedLanguage;
        notifyListeners();
      }
    } catch (e) {
      debugPrint('Error loading language preference: $e');
    }
  }

  // Change language and persist
  Future<void> changeLanguage(String languageCode) async {
    if (_languages.containsKey(languageCode)) {
      _currentLanguageCode = languageCode;

      // Save to SharedPreferences
      try {
        final prefs = await SharedPreferences.getInstance();
        await prefs.setString('app_language', languageCode);
      } catch (e) {
        debugPrint('Error saving language preference: $e');
      }

      notifyListeners();
    }
  }

  // Get translation for a key
  String translate(String key) {
    return _translations[_currentLanguageCode]?[key] ??
           _translations['en']?[key] ??
           key;
  }

  // Short form for translation
  String t(String key) => translate(key);

  // Translations map
  final Map<String, Map<String, String>> _translations = {
    'en': {
      // Common
      'app_name': 'MaxBillUp',
      'welcome': 'Welcome',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'add': 'Add',
      'update': 'Update',
      'search': 'Search',
      'settings': 'Settings',
      'logout': 'Logout',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'done': 'Done',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',

      // Navigation
      'home': 'Home',
      'sales': 'Sales',
      'stocks': 'Stocks',
      'reports': 'Reports',
      'menu': 'Menu',

      // Sales
      'new_sale': 'New Sale',
      'sale_all': 'Sale All',
      'quick_sale': 'Quick Sale',
      'saved_orders': 'Saved Orders',
      'complete_payment': 'Complete Payment',
      'add_to_cart': 'Add to Cart',
      'cart': 'Cart',
      'checkout': 'Checkout',
      'payment_mode': 'Payment Mode',
      'cash': 'Cash',
      'online': 'Online',
      'credit': 'Credit',
      'split_payment': 'Split Payment',

      // Bill
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'tax': 'Tax',
      'total': 'Total',
      'grand_total': 'Grand Total',
      'amount_received': 'Amount Received',
      'change': 'Change',
      'customer': 'Customer',
      'add_customer': 'Add Customer',

      // Products/Stocks
      'products': 'Products',
      'add_product': 'Add Product',
      'product_name': 'Product Name',
      'price': 'Price',
      'cost_price': 'Cost Price',
      'mrp': 'MRP',
      'quantity': 'Quantity',
      'category': 'Category',
      'barcode': 'Barcode',
      'stock': 'Stock',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'low_stock': 'Low Stock',

      // Tax
      'tax_settings': 'Tax Settings',
      'add_tax': 'Add Tax',
      'tax_name': 'Tax Name',
      'tax_percentage': 'Tax %',
      'price_includes_tax': 'Price includes Tax',
      'price_without_tax': 'Price is without Tax',
      'zero_rated_tax': 'Zero Rated Tax',
      'exempt_tax': 'Exempt Tax',

      // Settings
      'profile': 'Profile',
      'business_details': 'Business Details',
      'business_name': 'Business Name',
      'business_phone': 'Business Phone',
      'business_location': 'Business Location',
      'business_email': 'Business Email',
      'gstin': 'GSTIN',
      'choose_language': 'Choose Language',
      'theme': 'Theme',
      'printer_setup': 'Printer Setup',
      'receipt_customization': 'Receipt Customization',
      'feature_settings': 'Feature Settings',
      'help': 'Help',
      'about': 'About',

      // Reports
      'daily_report': 'Daily Report',
      'monthly_report': 'Monthly Report',
      'sales_report': 'Sales Report',
      'stock_report': 'Stock Report',
      'tax_report': 'Tax Report',
      'profit_loss': 'Profit & Loss',

      // Messages
      'product_added': 'Product added successfully',
      'product_updated': 'Product updated successfully',
      'product_deleted': 'Product deleted successfully',
      'sale_completed': 'Sale completed successfully',
      'payment_successful': 'Payment successful',
      'payment_failed': 'Payment failed',
      'no_items_in_cart': 'No items in cart',
      'invalid_input': 'Invalid input',
      'required_field': 'This field is required',
      'confirm_delete': 'Are you sure you want to delete?',
      'saved_offline': 'Saved offline. Will sync when online.',
      'sync_completed': 'Sync completed',

      // Additional Pages
      'quotations': 'Quotations',
      'create_quotation': 'Create Quotation',
      'quotation_list': 'Quotation List',
      'convert_to_sale': 'Convert to Sale',
      'expenses': 'Expenses',
      'other_expenses': 'Other Expenses',
      'add_expense': 'Add Expense',
      'expense_category': 'Expense Category',
      'categories': 'Categories',
      'add_category': 'Add Category',
      'staff_management': 'Staff Management',
      'add_staff': 'Add Staff',
      'customer_management': 'Customer Management',
      'customers': 'Customers',
      'supplier': 'Supplier',
      'purchase': 'Purchase',
      'stock_purchase': 'Stock Purchase',
      'view': 'View',
      'print': 'Print',
      'share': 'Share',
      'invoice': 'Invoice',
      'receipt': 'Receipt',
      'date': 'Date',
      'time': 'Time',
      'from': 'From',
      'to': 'To',
      'all': 'All',
      'today': 'Today',
      'yesterday': 'Yesterday',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'custom': 'Custom',
      'apply': 'Apply',
      'reset': 'Reset',
      'export': 'Export',
      'download': 'Download',
      'upload': 'Upload',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      'finish': 'Finish',
      'skip': 'Skip',
      'continue': 'Continue',
      'close': 'Close',
      'open': 'Open',
      'refresh': 'Refresh',
      'sync': 'Sync',
      'online_mode': 'Online Mode',
      'offline_mode': 'Offline Mode',
      'select': 'Select',
      'select_all': 'Select All',
      'deselect_all': 'Deselect All',
      'filter': 'Filter',
      'sort': 'Sort',
      'ascending': 'Ascending',
      'descending': 'Descending',
      'name': 'Name',
      'description': 'Description',
      'amount': 'Amount',
      'paid': 'Paid',
      'unpaid': 'Unpaid',
      'pending': 'Pending',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'active': 'Active',
      'inactive': 'Inactive',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'phone': 'Phone',
      'email': 'Email',
      'address': 'Address',
      'city': 'City',
      'state': 'State',
      'country': 'Country',
      'pincode': 'Pincode',
      'notes': 'Notes',
      'remarks': 'Remarks',
      'status': 'Status',
      'action': 'Action',
      'actions': 'Actions',
      'details': 'Details',
      'summary': 'Summary',
      'billing': 'Billing',
      'shipping': 'Shipping',
      'payment': 'Payment',
      'order': 'Order',
      'orders': 'Orders',
      'item': 'Item',
      'items': 'Items',
      'unit': 'Unit',
      'rate': 'Rate',
      'gst': 'GST',
      'vat': 'VAT',
      'cgst': 'CGST',
      'sgst': 'SGST',
      'igst': 'IGST',
      'total_items': 'Total Items',
      'total_amount': 'Total Amount',
      'due_amount': 'Due Amount',
      'balance': 'Balance',
      'credit_limit': 'Credit Limit',
      'available': 'Available',
      'unavailable': 'Unavailable',
    },

    'hi': {
      // Common
      'app_name': 'मैक्सबिलअप',
      'welcome': 'स्वागत है',
      'save': 'सेव करें',
      'cancel': 'रद्द करें',
      'delete': 'हटाएं',
      'edit': 'संपादित करें',
      'add': 'जोड़ें',
      'update': 'अपडेट करें',
      'search': 'खोजें',
      'settings': 'सेटिंग्स',
      'logout': 'लॉग आउट',
      'yes': 'हां',
      'no': 'नहीं',
      'ok': 'ठीक है',
      'done': 'हो गया',
      'loading': 'लोड हो रहा है...',
      'error': 'त्रुटि',
      'success': 'सफलता',

      // Navigation
      'home': 'होम',
      'sales': 'बिक्री',
      'stocks': 'स्टॉक',
      'reports': 'रिपोर्ट',
      'menu': 'मेनू',

      // Sales
      'new_sale': 'नई बिक्री',
      'sale_all': 'सभी बिक्री',
      'quick_sale': 'त्वरित बिक्री',
      'saved_orders': 'सहेजे गए आदेश',
      'complete_payment': 'भुगतान पूरा करें',
      'add_to_cart': 'कार्ट में जोड़ें',
      'cart': 'कार्ट',
      'checkout': 'चेकआउट',
      'payment_mode': 'भुगतान मोड',
      'cash': 'नकद',
      'online': 'ऑनलाइन',
      'credit': 'उधार',
      'split_payment': 'विभाजित भुगतान',

      // Bill
      'subtotal': 'उप-योग',
      'discount': 'छूट',
      'tax': 'कर',
      'total': 'कुल',
      'grand_total': 'कुल योग',
      'amount_received': 'प्राप्त राशि',
      'change': 'बदलाव',
      'customer': 'ग्राहक',
      'add_customer': 'ग्राहक जोड़ें',

      // Products/Stocks
      'products': 'उत्पाद',
      'add_product': 'उत्पाद जोड़ें',
      'product_name': 'उत्पाद का नाम',
      'price': 'मूल्य',
      'cost_price': 'लागत मूल्य',
      'mrp': 'एम.आर.पी',
      'quantity': 'मात्रा',
      'category': 'श्रेणी',
      'barcode': 'बारकोड',
      'stock': 'स्टॉक',
      'in_stock': 'स्टॉक में',
      'out_of_stock': 'स्टॉक खत्म',
      'low_stock': 'कम स्टॉक',

      // Tax
      'tax_settings': 'कर सेटिंग्स',
      'add_tax': 'कर जोड़ें',
      'tax_name': 'कर का नाम',
      'tax_percentage': 'कर %',
      'price_includes_tax': 'मूल्य में कर शामिल',
      'price_without_tax': 'मूल्य कर रहित',
      'zero_rated_tax': 'शून्य दर कर',
      'exempt_tax': 'कर मुक्त',

      // Settings
      'profile': 'प्रोफ़ाइल',
      'business_details': 'व्यापार विवरण',
      'business_name': 'व्यापार का नाम',
      'business_phone': 'व्यापार फोन',
      'business_location': 'व्यापार स्थान',
      'business_email': 'व्यापार ईमेल',
      'gstin': 'जीएसटीआईएन',
      'choose_language': 'भाषा चुनें',
      'theme': 'थीम',
      'printer_setup': 'प्रिंटर सेटअप',
      'receipt_customization': 'रसीद अनुकूलन',
      'feature_settings': 'फीचर सेटिंग्स',
      'help': 'मदद',
      'about': 'के बारे में',

      // Reports
      'daily_report': 'दैनिक रिपोर्ट',
      'monthly_report': 'मासिक रिपोर्ट',
      'sales_report': 'बिक्री रिपोर्ट',
      'stock_report': 'स्टॉक रिपोर्ट',
      'tax_report': 'कर रिपोर्ट',
      'profit_loss': 'लाभ और हानि',

      // Messages
      'product_added': 'उत्पाद सफलतापूर्वक जोड़ा गया',
      'product_updated': 'उत्पाद अपडेट किया गया',
      'product_deleted': 'उत्पाद हटाया गया',
      'sale_completed': 'बिक्री पूर्ण हुई',
      'payment_successful': 'भुगतान सफल',
      'payment_failed': 'भुगतान विफल',
      'no_items_in_cart': 'कार्ट में कोई आइटम नहीं',
      'invalid_input': 'अमान्य इनपुट',
      'required_field': 'यह फ़ील्ड आवश्यक है',
      'confirm_delete': 'क्या आप वाकई हटाना चाहते हैं?',
      'saved_offline': 'ऑफ़लाइन सहेजा गया। ऑनलाइन होने पर सिंक होगा।',
      'sync_completed': 'सिंक पूर्ण हुआ',

      // Additional Pages
      'quotations': 'कोटेशन',
      'create_quotation': 'कोटेशन बनाएं',
      'quotation_list': 'कोटेशन सूची',
      'convert_to_sale': 'बिक्री में बदलें',
      'expenses': 'खर्चे',
      'other_expenses': 'अन्य खर्चे',
      'add_expense': 'खर्च जोड़ें',
      'expense_category': 'खर्च श्रेणी',
      'categories': 'श्रेणियाँ',
      'add_category': 'श्रेणी जोड़ें',
      'staff_management': 'स्टाफ प्रबंधन',
      'add_staff': 'स्टाफ जोड़ें',
      'customer_management': 'ग्राहक प्रबंधन',
      'customers': 'ग्राहक',
      'supplier': 'आपूर्तिकर्ता',
      'purchase': 'खरीदी',
      'stock_purchase': 'स्टॉक खरीदी',
      'view': 'देखें',
      'print': 'प्रिंट करें',
      'share': 'साझा करें',
      'invoice': 'चालान',
      'receipt': 'रसीद',
      'date': 'तारीख',
      'time': 'समय',
      'from': 'से',
      'to': 'तक',
      'all': 'सभी',
      'today': 'आज',
      'yesterday': 'कल',
      'this_week': 'इस सप्ताह',
      'this_month': 'इस महीने',
      'custom': 'कस्टम',
      'apply': 'लागू करें',
      'reset': 'रीसेट करें',
      'export': 'निर्यात करें',
      'download': 'डाउनलोड करें',
      'upload': 'अपलोड करें',
      'back': 'वापस',
      'next': 'अगला',
      'previous': 'पिछला',
      'finish': 'समाप्त',
      'skip': 'छोड़ें',
      'continue': 'जारी रखें',
      'close': 'बंद करें',
      'open': 'खोलें',
      'refresh': 'ताज़ा करें',
      'sync': 'सिंक करें',
      'online_mode': 'ऑनलाइन मोड',
      'offline_mode': 'ऑफ़लाइन मोड',
      'select': 'चुनें',
      'select_all': 'सभी चुनें',
      'deselect_all': 'सभी अचयनित करें',
      'filter': 'फ़िल्टर',
      'sort': 'क्रमबद्ध करें',
      'ascending': 'बढ़ते क्रम में',
      'descending': 'घटते क्रम में',
      'name': 'नाम',
      'description': 'विवरण',
      'amount': 'राशि',
      'paid': 'भुगतान किया',
      'unpaid': 'अवैतनिक',
      'pending': 'लंबित',
      'completed': 'पूर्ण',
      'cancelled': 'रद्द',
      'active': 'सक्रिय',
      'inactive': 'निष्क्रिय',
      'enabled': 'सक्षम',
      'disabled': 'अक्षम',
      'phone': 'फोन',
      'email': 'ईमेल',
      'address': 'पता',
      'city': 'शहर',
      'state': 'राज्य',
      'country': 'देश',
      'pincode': 'पिनकोड',
      'notes': 'नोट्स',
      'remarks': 'टिप्पणी',
      'status': 'स्थिति',
      'action': 'कार्रवाई',
      'actions': 'कार्रवाईयाँ',
      'details': 'विवरण',
      'summary': 'सारांश',
      'billing': 'बिलिंग',
      'shipping': 'शिपिंग',
      'payment': 'भुगतान',
      'order': 'आदेश',
      'orders': 'आदेश',
      'item': 'आइटम',
      'items': 'आइटम',
      'unit': 'इकाई',
      'rate': 'दर',
      'gst': 'जीएसटी',
      'vat': 'वैट',
      'cgst': 'सीजीएसटी',
      'sgst': 'एसजीएसटी',
      'igst': 'आईजीएसटी',
      'total_items': 'कुल आइटम',
      'total_amount': 'कुल राशि',
      'due_amount': 'बकाया राशि',
      'balance': 'शेष',
      'credit_limit': 'क्रेडिट सीमा',
      'available': 'उपलब्ध',
      'unavailable': 'अनुपलब्ध',
    },

    'ta': {
      // Common
      'app_name': 'மேக்ஸ்பில்அப்',
      'welcome': 'வரவேற்கிறோம்',
      'save': 'சேமி',
      'cancel': 'ரத்து',
      'delete': 'நீக்கு',
      'edit': 'திருத்து',
      'add': 'சேர்',
      'update': 'புதுப்பி',
      'search': 'தேடு',
      'settings': 'அமைப்புகள்',
      'logout': 'வெளியேறு',
      'yes': 'ஆம்',
      'no': 'இல்லை',
      'ok': 'சரி',
      'done': 'முடிந்தது',
      'loading': 'ஏற்றுகிறது...',
      'error': 'பிழை',
      'success': 'வெற்றி',

      // Navigation
      'home': 'முகப்பு',
      'sales': 'விற்பனை',
      'stocks': 'சரக்கு',
      'reports': 'அறிக்கைகள்',
      'menu': 'பட்டியல்',

      // Sales
      'new_sale': 'புதிய விற்பனை',
      'sale_all': 'அனைத்து விற்பனை',
      'quick_sale': 'விரைவு விற்பனை',
      'saved_orders': 'சேமித்த ஆர்டர்கள்',
      'complete_payment': 'கட்டணம் முடிக்கவும்',
      'add_to_cart': 'வண்டியில் சேர்',
      'cart': 'வண்டி',
      'checkout': 'செக்அவுட்',
      'payment_mode': 'கட்டண முறை',
      'cash': 'பணம்',
      'online': 'ஆன்லைன்',
      'credit': 'கடன்',
      'split_payment': 'பிரிக்கப்பட்ட கட்டணம்',

      // Bill
      'subtotal': 'துணை மொத்தம்',
      'discount': 'தள்ளுபடி',
      'tax': 'வரி',
      'total': 'மொத்தம்',
      'grand_total': 'பெரும் மொத்தம்',
      'amount_received': 'பெறப்பட்ட தொகை',
      'change': 'மாற்றம்',
      'customer': 'வாடிக்கையாளர்',
      'add_customer': 'வாடிக்கையாளர் சேர்',

      // Products/Stocks
      'products': 'பொருட்கள்',
      'add_product': 'பொருள் சேர்',
      'product_name': 'பொருளின் பெயர்',
      'price': 'விலை',
      'cost_price': 'செலவு விலை',
      'mrp': 'எம்.ஆர்.பி',
      'quantity': 'அளவு',
      'category': 'வகை',
      'barcode': 'பார்கோடு',
      'stock': 'சரக்கு',
      'in_stock': 'சரக்கில் உள்ளது',
      'out_of_stock': 'சரக்கு தீர்ந்தது',
      'low_stock': 'குறைவான சரக்கு',

      // Tax
      'tax_settings': 'வரி அமைப்புகள்',
      'add_tax': 'வரி சேர்',
      'tax_name': 'வரி பெயர்',
      'tax_percentage': 'வரி %',
      'price_includes_tax': 'விலையில் வரி உள்ளது',
      'price_without_tax': 'வரி இல்லாத விலை',
      'zero_rated_tax': 'பூஜ்ஜிய வரி',
      'exempt_tax': 'வரி விலக்கு',

      // Settings
      'profile': 'சுயவிவரம்',
      'business_details': 'வணிக விவரங்கள்',
      'business_name': 'வணிக பெயர்',
      'business_phone': 'வணிக தொலைபேசி',
      'business_location': 'வணிக இடம்',
      'business_email': 'வணிக மின்னஞ்சல்',
      'gstin': 'ஜிஎஸ்டிஐஎன்',
      'choose_language': 'மொழியைத் தேர்ந்தெடு',
      'theme': 'தீம்',
      'printer_setup': 'அச்சுப்பொறி அமைப்பு',
      'receipt_customization': 'ரசீது தனிப்பயனாக்கம்',
      'feature_settings': 'அம்ச அமைப்புகள்',
      'help': 'உதவி',
      'about': 'பற்றி',

      // Reports
      'daily_report': 'தினசரி அறிக்கை',
      'monthly_report': 'மாதாந்திர அறிக்கை',
      'sales_report': 'விற்பனை அறிக்கை',
      'stock_report': 'சரக்கு அறிக்கை',
      'tax_report': 'வரி அறிக்கை',
      'profit_loss': 'இலாபம் & நஷ்டம்',

      // Messages
      'product_added': 'பொருள் வெற்றிகரமாக சேர்க்கப்பட்டது',
      'product_updated': 'பொருள் புதுப்பிக்கப்பட்டது',
      'product_deleted': 'பொருள் நீக்கப்பட்டது',
      'sale_completed': 'விற்பனை முடிந்தது',
      'payment_successful': 'கட்டணம் வெற்றி',
      'payment_failed': 'கட்டணம் தோல்வி',
      'no_items_in_cart': 'வண்டியில் பொருட்கள் இல்லை',
      'invalid_input': 'தவறான உள்ளீடு',
      'required_field': 'இந்த புலம் தேவை',
      'confirm_delete': 'நிச்சயமாக நீக்க விரும்புகிறீர்களா?',
      'saved_offline': 'ஆஃப்லைனில் சேமிக்கப்பட்டது. ஆன்லைனில் ஒத்திசைக்கப்படும்.',
      'sync_completed': 'ஒத்திசைவு முடிந்தது',

      // Additional Pages
      'quotations': 'மேற்கோள்கள்',
      'create_quotation': 'மேற்கோள் உருவாக்கு',
      'quotation_list': 'மேற்கோள் பட்டியல்',
      'convert_to_sale': 'விற்பனையாக மாற்று',
      'expenses': 'செலவுகள்',
      'other_expenses': 'பிற செலவுகள்',
      'add_expense': 'செலவு சேர்',
      'expense_category': 'செலவு வகை',
      'categories': 'வகைகள்',
      'add_category': 'வகை சேர்',
      'staff_management': 'பணியாளர் மேலாண்மை',
      'add_staff': 'பணியாளர் சேர்',
      'customer_management': 'வாடிக்கையாளர் மேலாண்மை',
      'customers': 'வாடிக்கையாளர்கள்',
      'supplier': 'விநியோகஸ்தர்',
      'purchase': 'கொள்முதல்',
      'stock_purchase': 'சரக்கு கொள்முதல்',
      'view': 'காண்க',
      'print': 'அச்சிடு',
      'share': 'பகிர்',
      'invoice': 'இன்வாய்ஸ்',
      'receipt': 'ரசீது',
      'date': 'தேதி',
      'time': 'நேரம்',
      'from': 'இருந்து',
      'to': 'வரை',
      'all': 'அனைத்தும்',
      'today': 'இன்று',
      'yesterday': 'நேற்று',
      'this_week': 'இந்த வாரம்',
      'this_month': 'இந்த மாதம்',
      'custom': 'தனிப்பயன்',
      'apply': 'பயன்படுத்து',
      'reset': 'மீட்டமை',
      'export': 'ஏற்றுமதி',
      'download': 'பதிவிறக்கு',
      'upload': 'பதிவேற்று',
      'back': 'பின்',
      'next': 'அடுத்து',
      'previous': 'முந்தைய',
      'finish': 'முடி',
      'skip': 'தவிர்',
      'continue': 'தொடர்',
      'close': 'மூடு',
      'open': 'திற',
      'refresh': 'புதுப்பி',
      'sync': 'ஒத்திசை',
      'online_mode': 'ஆன்லைன் பயன்முறை',
      'offline_mode': 'ஆஃப்லைன் பயன்முறை',
      'select': 'தேர்ந்தெடு',
      'select_all': 'அனைத்தையும் தேர்ந்தெடு',
      'deselect_all': 'அனைத்தையும் தேர்வு நீக்கு',
      'filter': 'வடிகட்டு',
      'sort': 'வரிசைப்படுத்து',
      'ascending': 'ஏறுவரிசை',
      'descending': 'இறங்குவரிசை',
      'name': 'பெயர்',
      'description': 'விளக்கம்',
      'amount': 'தொகை',
      'paid': 'செலுத்தப்பட்டது',
      'unpaid': 'செலுத்தப்படாதது',
      'pending': 'நிலுவையில்',
      'completed': 'முடிந்தது',
      'cancelled': 'ரத்து செய்யப்பட்டது',
      'active': 'செயல்படும்',
      'inactive': 'செயலற்றது',
      'enabled': 'இயக்கப்பட்டது',
      'disabled': 'முடக்கப்பட்டது',
      'phone': 'தொலைபேசி',
      'email': 'மின்னஞ்சல்',
      'address': 'முகவரி',
      'city': 'நகரம்',
      'state': 'மாநிலம்',
      'country': 'நாடு',
      'pincode': 'பின்கோட்',
      'notes': 'குறிப்புகள்',
      'remarks': 'கருத்துகள்',
      'status': 'நிலை',
      'action': 'செயல்',
      'actions': 'செயல்கள்',
      'details': 'விவரங்கள்',
      'summary': 'சுருக்கம்',
      'billing': 'பில்லிங்',
      'shipping': 'ஷிப்பிங்',
      'payment': 'கட்டணம்',
      'order': 'ஆர்டர்',
      'orders': 'ஆர்டர்கள்',
      'item': 'பொருள்',
      'items': 'பொருட்கள்',
      'unit': 'அலகு',
      'rate': 'விலை',
      'gst': 'ஜிஎஸ்டி',
      'vat': 'வேட்',
      'cgst': 'சிஜிஎஸ்டி',
      'sgst': 'எஸ்ஜிஎஸ்டி',
      'igst': 'ஐஜிஎஸ்டி',
      'total_items': 'மொத்த பொருட்கள்',
      'total_amount': 'மொத்த தொகை',
      'due_amount': 'நிலுவை தொகை',
      'balance': 'இருப்பு',
      'credit_limit': 'கடன் வரம்பு',
      'available': 'கிடைக்கிறது',
      'unavailable': 'கிடைக்கவில்லை',
    },
  };
}

